/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Jacobian of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_Jacobian.c                        */
/* Time                 : Tue Feb  1 10:46:30 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_Parameters.h"
#include "tm5_ifs_Global.h"
#include "tm5_ifs_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Jac_SP - the Jacobian of Variables in sparse matrix representation */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      JVS       - sparse Jacobian of variables                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Jac_SP( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double JVS[]                           /* sparse Jacobian of variables */
)
{

/* Local variables                                                  */
double B[65];                            /* Temporary array */

/* B(0) = dA(0)/dV(10)                                              */
  B[0] = RCT[0]*V[13];
/* B(1) = dA(0)/dV(13)                                              */
  B[1] = RCT[0]*V[10];
/* B(2) = dA(1)/dV(8)                                               */
  B[2] = RCT[1]*V[10];
/* B(3) = dA(1)/dV(10)                                              */
  B[3] = RCT[1]*V[8];
/* B(4) = dA(2)/dV(8)                                               */
  B[4] = RCT[2]*V[13];
/* B(5) = dA(2)/dV(13)                                              */
  B[5] = RCT[2]*V[8];
/* B(6) = dA(3)/dV(8)                                               */
  B[6] = RCT[3]*2*V[8];
/* B(7) = dA(4)/dV(2)                                               */
  B[7] = RCT[4]*V[13];
/* B(8) = dA(4)/dV(13)                                              */
  B[8] = RCT[4]*V[2];
/* B(9) = dA(5)/dV(13)                                              */
  B[9] = RCT[5];
/* B(10) = dA(6)/dV(10)                                             */
  B[10] = RCT[6]*V[12];
/* B(11) = dA(6)/dV(12)                                             */
  B[11] = RCT[6]*V[10];
/* B(12) = dA(7)/dV(8)                                              */
  B[12] = RCT[7]*V[12];
/* B(13) = dA(7)/dV(12)                                             */
  B[13] = RCT[7]*V[8];
/* B(14) = dA(8)/dV(11)                                             */
  B[14] = RCT[8]*V[13];
/* B(15) = dA(8)/dV(13)                                             */
  B[15] = RCT[8]*V[11];
/* B(16) = dA(9)/dV(13)                                             */
  B[16] = RCT[9]*F[0];
/* B(18) = dA(10)/dV(7)                                             */
  B[18] = RCT[10]*V[12];
/* B(19) = dA(10)/dV(12)                                            */
  B[19] = RCT[10]*V[7];
/* B(20) = dA(11)/dV(7)                                             */
  B[20] = RCT[11]*V[8];
/* B(21) = dA(11)/dV(8)                                             */
  B[21] = RCT[11]*V[7];
/* B(22) = dA(12)/dV(7)                                             */
  B[22] = RCT[12]*V[8];
/* B(23) = dA(12)/dV(8)                                             */
  B[23] = RCT[12]*V[7];
/* B(24) = dA(13)/dV(4)                                             */
  B[24] = RCT[13]*V[13];
/* B(25) = dA(13)/dV(13)                                            */
  B[25] = RCT[13]*V[4];
/* B(26) = dA(14)/dV(4)                                             */
  B[26] = 2e-11*V[13];
/* B(27) = dA(14)/dV(13)                                            */
  B[27] = 2e-11*V[4];
/* B(28) = dA(15)/dV(3)                                             */
  B[28] = RCT[15]*V[13];
/* B(29) = dA(15)/dV(13)                                            */
  B[29] = RCT[15]*V[3];
/* B(30) = dA(16)/dV(5)                                             */
  B[30] = RCT[16]*V[13];
/* B(31) = dA(16)/dV(13)                                            */
  B[31] = RCT[16]*V[5];
/* B(32) = dA(17)/dV(6)                                             */
  B[32] = RCT[17]*V[10];
/* B(33) = dA(17)/dV(10)                                            */
  B[33] = RCT[17]*V[6];
/* B(34) = dA(18)/dV(6)                                             */
  B[34] = RCT[18]*V[13];
/* B(35) = dA(18)/dV(13)                                            */
  B[35] = RCT[18]*V[6];
/* B(36) = dA(19)/dV(10)                                            */
  B[36] = RCT[19];
/* B(37) = dA(20)/dV(11)                                            */
  B[37] = RCT[20];
/* B(38) = dA(21)/dV(5)                                             */
  B[38] = RCT[21];
/* B(39) = dA(22)/dV(5)                                             */
  B[39] = RCT[22];
/* B(40) = dA(23)/dV(4)                                             */
  B[40] = RCT[23];
/* B(41) = dA(24)/dV(2)                                             */
  B[41] = RCT[24];
/* B(42) = dA(25)/dV(10)                                            */
  B[42] = RCT[25]*V[11];
/* B(43) = dA(25)/dV(11)                                            */
  B[43] = RCT[25]*V[10];
/* B(44) = dA(26)/dV(9)                                             */
  B[44] = RCT[26]*V[12];
/* B(45) = dA(26)/dV(12)                                            */
  B[45] = RCT[26]*V[9];
/* B(46) = dA(27)/dV(9)                                             */
  B[46] = RCT[27]*V[11];
/* B(47) = dA(27)/dV(11)                                            */
  B[47] = RCT[27]*V[9];
/* B(48) = dA(28)/dV(1)                                             */
  B[48] = RCT[28];
/* B(49) = dA(29)/dV(8)                                             */
  B[49] = 4e-12*V[9];
/* B(50) = dA(29)/dV(9)                                             */
  B[50] = 4e-12*V[8];
/* B(51) = dA(30)/dV(1)                                             */
  B[51] = 1.5e-21;
/* B(52) = dA(31)/dV(6)                                             */
  B[52] = RCT[31]*V[9];
/* B(53) = dA(31)/dV(9)                                             */
  B[53] = RCT[31]*V[6];
/* B(54) = dA(32)/dV(9)                                             */
  B[54] = RCT[32];
/* B(55) = dA(33)/dV(1)                                             */
  B[55] = RCT[33];
/* B(58) = dA(36)/dV(10)                                            */
  B[58] = RCT[36];
/* B(59) = dA(37)/dV(12)                                            */
  B[59] = RCT[37];
/* B(60) = dA(38)/dV(11)                                            */
  B[60] = RCT[38];
/* B(61) = dA(39)/dV(0)                                             */
  B[61] = RCT[39];
/* B(62) = dA(40)/dV(4)                                             */
  B[62] = RCT[40];
/* B(63) = dA(41)/dV(2)                                             */
  B[63] = RCT[41];
/* B(64) = dA(42)/dV(5)                                             */
  B[64] = RCT[42];

/* Construct the Jacobian terms from B's                            */
/* JVS(0) = Jac_FULL(0,0)                                           */
  JVS[0] = -B[61];
/* JVS(1) = Jac_FULL(0,1)                                           */
  JVS[1] = 2*B[51];
/* JVS(2) = Jac_FULL(0,8)                                           */
  JVS[2] = B[49];
/* JVS(3) = Jac_FULL(0,9)                                           */
  JVS[3] = B[50];
/* JVS(4) = Jac_FULL(0,11)                                          */
  JVS[4] = B[14];
/* JVS(5) = Jac_FULL(0,13)                                          */
  JVS[5] = B[15];
/* JVS(6) = Jac_FULL(1,1)                                           */
  JVS[6] = -B[48]-B[51]-B[55];
/* JVS(7) = Jac_FULL(1,9)                                           */
  JVS[7] = B[46];
/* JVS(8) = Jac_FULL(1,11)                                          */
  JVS[8] = B[47];
/* JVS(9) = Jac_FULL(2,2)                                           */
  JVS[9] = -B[7]-B[41]-B[63];
/* JVS(10) = Jac_FULL(2,8)                                          */
  JVS[10] = B[6];
/* JVS(11) = Jac_FULL(2,13)                                         */
  JVS[11] = -B[8];
/* JVS(12) = Jac_FULL(3,3)                                          */
  JVS[12] = -B[28];
/* JVS(13) = Jac_FULL(3,5)                                          */
  JVS[13] = B[30]+B[38]+B[39];
/* JVS(14) = Jac_FULL(3,6)                                          */
  JVS[14] = 0.56*B[32];
/* JVS(15) = Jac_FULL(3,10)                                         */
  JVS[15] = 0.56*B[33];
/* JVS(16) = Jac_FULL(3,13)                                         */
  JVS[16] = -B[29]+B[31];
/* JVS(17) = Jac_FULL(4,4)                                          */
  JVS[17] = -B[24]-B[26]-B[40]-B[62];
/* JVS(18) = Jac_FULL(4,7)                                          */
  JVS[18] = B[20];
/* JVS(19) = Jac_FULL(4,8)                                          */
  JVS[19] = B[21];
/* JVS(20) = Jac_FULL(4,13)                                         */
  JVS[20] = -B[25]-B[27];
/* JVS(21) = Jac_FULL(5,4)                                          */
  JVS[21] = 0.4*B[24]+B[40];
/* JVS(22) = Jac_FULL(5,5)                                          */
  JVS[22] = -B[30]-B[38]-B[39]-B[64];
/* JVS(23) = Jac_FULL(5,6)                                          */
  JVS[23] = 0.54*B[32];
/* JVS(24) = Jac_FULL(5,7)                                          */
  JVS[24] = B[18]+B[22];
/* JVS(25) = Jac_FULL(5,8)                                          */
  JVS[25] = B[23];
/* JVS(26) = Jac_FULL(5,10)                                         */
  JVS[26] = 0.54*B[33];
/* JVS(27) = Jac_FULL(5,12)                                         */
  JVS[27] = B[19];
/* JVS(28) = Jac_FULL(5,13)                                         */
  JVS[28] = 0.4*B[25]-B[31];
/* JVS(29) = Jac_FULL(6,6)                                          */
  JVS[29] = -B[32]-B[34]-B[52];
/* JVS(30) = Jac_FULL(6,9)                                          */
  JVS[30] = -B[53];
/* JVS(31) = Jac_FULL(6,10)                                         */
  JVS[31] = -B[33];
/* JVS(32) = Jac_FULL(6,13)                                         */
  JVS[32] = -B[35];
/* JVS(33) = Jac_FULL(7,4)                                          */
  JVS[33] = 0.6*B[24];
/* JVS(34) = Jac_FULL(7,6)                                          */
  JVS[34] = 0.31*B[32]+B[34]+B[52];
/* JVS(35) = Jac_FULL(7,7)                                          */
  JVS[35] = -B[18]-B[20]-B[22];
/* JVS(36) = Jac_FULL(7,8)                                          */
  JVS[36] = -B[21]-B[23];
/* JVS(37) = Jac_FULL(7,9)                                          */
  JVS[37] = B[53];
/* JVS(38) = Jac_FULL(7,10)                                         */
  JVS[38] = 0.31*B[33];
/* JVS(39) = Jac_FULL(7,12)                                         */
  JVS[39] = -B[19];
/* JVS(40) = Jac_FULL(7,13)                                         */
  JVS[40] = B[16]+0.6*B[25]+B[35];
/* JVS(41) = Jac_FULL(8,2)                                          */
  JVS[41] = B[7];
/* JVS(42) = Jac_FULL(8,3)                                          */
  JVS[42] = B[28];
/* JVS(43) = Jac_FULL(8,4)                                          */
  JVS[43] = B[40];
/* JVS(44) = Jac_FULL(8,5)                                          */
  JVS[44] = B[30]+2*B[38];
/* JVS(45) = Jac_FULL(8,6)                                          */
  JVS[45] = 0.19*B[32];
/* JVS(46) = Jac_FULL(8,7)                                          */
  JVS[46] = B[18]-B[20]-B[22];
/* JVS(47) = Jac_FULL(8,8)                                          */
  JVS[47] = -B[2]-B[4]-2*B[6]-B[12]-B[21]-B[23]-B[49];
/* JVS(48) = Jac_FULL(8,9)                                          */
  JVS[48] = -B[50];
/* JVS(49) = Jac_FULL(8,10)                                         */
  JVS[49] = B[0]-B[3]+0.19*B[33];
/* JVS(50) = Jac_FULL(8,12)                                         */
  JVS[50] = -B[13]+B[19];
/* JVS(51) = Jac_FULL(8,13)                                         */
  JVS[51] = B[1]-B[5]+B[8]+B[9]+B[29]+B[31];
/* JVS(52) = Jac_FULL(9,1)                                          */
  JVS[52] = B[48]+B[55];
/* JVS(53) = Jac_FULL(9,6)                                          */
  JVS[53] = -B[52];
/* JVS(54) = Jac_FULL(9,8)                                          */
  JVS[54] = -B[49];
/* JVS(55) = Jac_FULL(9,9)                                          */
  JVS[55] = -B[44]-B[46]-B[50]-B[53]-B[54];
/* JVS(56) = Jac_FULL(9,10)                                         */
  JVS[56] = B[42];
/* JVS(57) = Jac_FULL(9,11)                                         */
  JVS[57] = B[43]-B[47];
/* JVS(58) = Jac_FULL(9,12)                                         */
  JVS[58] = -B[45];
/* JVS(59) = Jac_FULL(9,13)                                         */
  JVS[59] = 0;
/* JVS(60) = Jac_FULL(10,6)                                         */
  JVS[60] = -B[32];
/* JVS(61) = Jac_FULL(10,8)                                         */
  JVS[61] = -B[2];
/* JVS(62) = Jac_FULL(10,9)                                         */
  JVS[62] = B[54];
/* JVS(63) = Jac_FULL(10,10)                                        */
  JVS[63] = -B[0]-B[3]-B[10]-B[33]-B[36]-B[42]-B[58];
/* JVS(64) = Jac_FULL(10,11)                                        */
  JVS[64] = B[37]-B[43];
/* JVS(65) = Jac_FULL(10,12)                                        */
  JVS[65] = -B[11];
/* JVS(66) = Jac_FULL(10,13)                                        */
  JVS[66] = -B[1];
/* JVS(67) = Jac_FULL(11,1)                                         */
  JVS[67] = B[48]+B[55];
/* JVS(68) = Jac_FULL(11,6)                                         */
  JVS[68] = B[52];
/* JVS(69) = Jac_FULL(11,7)                                         */
  JVS[69] = B[18];
/* JVS(70) = Jac_FULL(11,8)                                         */
  JVS[70] = B[12];
/* JVS(71) = Jac_FULL(11,9)                                         */
  JVS[71] = 2*B[44]-B[46]+B[53]+B[54];
/* JVS(72) = Jac_FULL(11,10)                                        */
  JVS[72] = B[10]-B[42];
/* JVS(73) = Jac_FULL(11,11)                                        */
  JVS[73] = -B[14]-B[37]-B[43]-B[47]-B[60];
/* JVS(74) = Jac_FULL(11,12)                                        */
  JVS[74] = B[11]+B[13]+B[19]+2*B[45];
/* JVS(75) = Jac_FULL(11,13)                                        */
  JVS[75] = -B[15];
/* JVS(76) = Jac_FULL(12,7)                                         */
  JVS[76] = -B[18];
/* JVS(77) = Jac_FULL(12,8)                                         */
  JVS[77] = -B[12];
/* JVS(78) = Jac_FULL(12,9)                                         */
  JVS[78] = -B[44];
/* JVS(79) = Jac_FULL(12,10)                                        */
  JVS[79] = -B[10];
/* JVS(80) = Jac_FULL(12,11)                                        */
  JVS[80] = B[37];
/* JVS(81) = Jac_FULL(12,12)                                        */
  JVS[81] = -B[11]-B[13]-B[19]-B[45]-B[59];
/* JVS(82) = Jac_FULL(12,13)                                        */
  JVS[82] = 0;
/* JVS(83) = Jac_FULL(13,2)                                         */
  JVS[83] = -B[7]+2*B[41];
/* JVS(84) = Jac_FULL(13,3)                                         */
  JVS[84] = -B[28];
/* JVS(85) = Jac_FULL(13,4)                                         */
  JVS[85] = -0.6*B[24]-0.77*B[26]+B[40];
/* JVS(86) = Jac_FULL(13,5)                                         */
  JVS[86] = -B[30];
/* JVS(87) = Jac_FULL(13,6)                                         */
  JVS[87] = 0.33*B[32]-B[34];
/* JVS(88) = Jac_FULL(13,7)                                         */
  JVS[88] = 0;
/* JVS(89) = Jac_FULL(13,8)                                         */
  JVS[89] = B[2]-B[4]+B[12];
/* JVS(90) = Jac_FULL(13,9)                                         */
  JVS[90] = 0;
/* JVS(91) = Jac_FULL(13,10)                                        */
  JVS[91] = -B[0]+B[3]+0.33*B[33]+2*B[36];
/* JVS(92) = Jac_FULL(13,11)                                        */
  JVS[92] = -B[14];
/* JVS(93) = Jac_FULL(13,12)                                        */
  JVS[93] = B[13];
/* JVS(94) = Jac_FULL(13,13)                                        */
  JVS[94] = -B[1]-B[5]-B[8]-B[9]-B[15]-B[16]-0.6*B[25]-0.77*B[27]-B[29]
           -B[31]-B[35];
}

/* End of Jac_SP function                                           */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector */
/*   Arguments :                                                    */
/*      JVS       - sparse Jacobian of variables                    */
/*      UV        - User vector for variables                       */
/*      JUV       - Jacobian times user vector                      */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Jac_SP_Vec( 
  double JVS[],                          /* sparse Jacobian of variables */
  double UV[],                           /* User vector for variables */
  double JUV[]                           /* Jacobian times user vector */
)
{
  JUV[0] = JVS[0]*UV[0]+JVS[1]*UV[1]+JVS[2]*UV[8]+JVS[3]*UV[9]+JVS[4]
          *UV[11]+JVS[5]*UV[13];
  JUV[1] = JVS[6]*UV[1]+JVS[7]*UV[9]+JVS[8]*UV[11];
  JUV[2] = JVS[9]*UV[2]+JVS[10]*UV[8]+JVS[11]*UV[13];
  JUV[3] = JVS[12]*UV[3]+JVS[13]*UV[5]+JVS[14]*UV[6]+JVS[15]*UV[10]
          +JVS[16]*UV[13];
  JUV[4] = JVS[17]*UV[4]+JVS[18]*UV[7]+JVS[19]*UV[8]+JVS[20]*UV[13];
  JUV[5] = JVS[21]*UV[4]+JVS[22]*UV[5]+JVS[23]*UV[6]+JVS[24]*UV[7]
          +JVS[25]*UV[8]+JVS[26]*UV[10]+JVS[27]*UV[12]+JVS[28]*UV[13];
  JUV[6] = JVS[29]*UV[6]+JVS[30]*UV[9]+JVS[31]*UV[10]+JVS[32]*UV[13];
  JUV[7] = JVS[33]*UV[4]+JVS[34]*UV[6]+JVS[35]*UV[7]+JVS[36]*UV[8]
          +JVS[37]*UV[9]+JVS[38]*UV[10]+JVS[39]*UV[12]+JVS[40]*UV[13];
  JUV[8] = JVS[41]*UV[2]+JVS[42]*UV[3]+JVS[43]*UV[4]+JVS[44]*UV[5]
          +JVS[45]*UV[6]+JVS[46]*UV[7]+JVS[47]*UV[8]+JVS[48]*UV[9]
          +JVS[49]*UV[10]+JVS[50]*UV[12]+JVS[51]*UV[13];
  JUV[9] = JVS[52]*UV[1]+JVS[53]*UV[6]+JVS[54]*UV[8]+JVS[55]*UV[9]
          +JVS[56]*UV[10]+JVS[57]*UV[11]+JVS[58]*UV[12];
  JUV[10] = JVS[60]*UV[6]+JVS[61]*UV[8]+JVS[62]*UV[9]+JVS[63]*UV[10]
           +JVS[64]*UV[11]+JVS[65]*UV[12]+JVS[66]*UV[13];
  JUV[11] = JVS[67]*UV[1]+JVS[68]*UV[6]+JVS[69]*UV[7]+JVS[70]*UV[8]
           +JVS[71]*UV[9]+JVS[72]*UV[10]+JVS[73]*UV[11]+JVS[74]*UV[12]
           +JVS[75]*UV[13];
  JUV[12] = JVS[76]*UV[7]+JVS[77]*UV[8]+JVS[78]*UV[9]+JVS[79]*UV[10]
           +JVS[80]*UV[11]+JVS[81]*UV[12];
  JUV[13] = JVS[83]*UV[2]+JVS[84]*UV[3]+JVS[85]*UV[4]+JVS[86]*UV[5]
           +JVS[87]*UV[6]+JVS[89]*UV[8]+JVS[91]*UV[10]+JVS[92]*UV[11]
           +JVS[93]*UV[12]+JVS[94]*UV[13];
}

/* End of Jac_SP_Vec function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector */
/*   Arguments :                                                    */
/*      JVS       - sparse Jacobian of variables                    */
/*      UV        - User vector for variables                       */
/*      JTUV      - Jacobian transposed times user vector           */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void JacTR_SP_Vec( 
  double JVS[],                          /* sparse Jacobian of variables */
  double UV[],                           /* User vector for variables */
  double JTUV[]                          /* Jacobian transposed times user vector */
)
{
  JTUV[0] = JVS[0]*UV[0];
  JTUV[1] = JVS[1]*UV[0]+JVS[6]*UV[1]+JVS[52]*UV[9]+JVS[67]*UV[11];
  JTUV[2] = JVS[9]*UV[2]+JVS[41]*UV[8]+JVS[83]*UV[13];
  JTUV[3] = JVS[12]*UV[3]+JVS[42]*UV[8]+JVS[84]*UV[13];
  JTUV[4] = JVS[17]*UV[4]+JVS[21]*UV[5]+JVS[33]*UV[7]+JVS[43]*UV[8]
           +JVS[85]*UV[13];
  JTUV[5] = JVS[13]*UV[3]+JVS[22]*UV[5]+JVS[44]*UV[8]+JVS[86]*UV[13];
  JTUV[6] = JVS[14]*UV[3]+JVS[23]*UV[5]+JVS[29]*UV[6]+JVS[34]*UV[7]
           +JVS[45]*UV[8]+JVS[53]*UV[9]+JVS[60]*UV[10]+JVS[68]*UV[11]
           +JVS[87]*UV[13];
  JTUV[7] = JVS[18]*UV[4]+JVS[24]*UV[5]+JVS[35]*UV[7]+JVS[46]*UV[8]
           +JVS[69]*UV[11]+JVS[76]*UV[12];
  JTUV[8] = JVS[2]*UV[0]+JVS[10]*UV[2]+JVS[19]*UV[4]+JVS[25]*UV[5]
           +JVS[36]*UV[7]+JVS[47]*UV[8]+JVS[54]*UV[9]+JVS[61]*UV[10]
           +JVS[70]*UV[11]+JVS[77]*UV[12]+JVS[89]*UV[13];
  JTUV[9] = JVS[3]*UV[0]+JVS[7]*UV[1]+JVS[30]*UV[6]+JVS[37]*UV[7]
           +JVS[48]*UV[8]+JVS[55]*UV[9]+JVS[62]*UV[10]+JVS[71]*UV[11]
           +JVS[78]*UV[12];
  JTUV[10] = JVS[15]*UV[3]+JVS[26]*UV[5]+JVS[31]*UV[6]+JVS[38]*UV[7]
            +JVS[49]*UV[8]+JVS[56]*UV[9]+JVS[63]*UV[10]+JVS[72]*UV[11]
            +JVS[79]*UV[12]+JVS[91]*UV[13];
  JTUV[11] = JVS[4]*UV[0]+JVS[8]*UV[1]+JVS[57]*UV[9]+JVS[64]*UV[10]
            +JVS[73]*UV[11]+JVS[80]*UV[12]+JVS[92]*UV[13];
  JTUV[12] = JVS[27]*UV[5]+JVS[39]*UV[7]+JVS[50]*UV[8]+JVS[58]*UV[9]
            +JVS[65]*UV[10]+JVS[74]*UV[11]+JVS[81]*UV[12]+JVS[93]
            *UV[13];
  JTUV[13] = JVS[5]*UV[0]+JVS[11]*UV[2]+JVS[16]*UV[3]+JVS[20]*UV[4]
            +JVS[28]*UV[5]+JVS[32]*UV[6]+JVS[40]*UV[7]+JVS[51]*UV[8]
            +JVS[66]*UV[10]+JVS[75]*UV[11]+JVS[94]*UV[13];
}

/* End of JacTR_SP_Vec function                                     */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


