/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialization File                                              */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_22_Initialize.c                   */
/* Time                 : Wed Oct 12 11:08:37 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs_22.kpp                            */
/* Output root filename : tm5_ifs_22                                */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_22_Parameters.h"
#include "tm5_ifs_22_Global.h"
#include "tm5_ifs_22_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialize - function to initialize concentrations               */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Initialize( 
)
{
int i;                                  
double x;                               

  CFACTOR = 2.550000e+10;

  x = (0.)*CFACTOR;
  for( i = 0; i < NVAR; i++ )
    VAR[i] = x;

  x = (0.)*CFACTOR;
  for( i = 0; i < NFIX; i++ )
    FIX[i] = x;

  VAR[0] = (1.)*CFACTOR;
  VAR[2] = (100.)*CFACTOR;
  VAR[3] = (1.)*CFACTOR;
  VAR[4] = (1.)*CFACTOR;
  VAR[6] = (1.)*CFACTOR;
  VAR[7] = (0.6)*CFACTOR;
  VAR[8] = (30.)*CFACTOR;
  VAR[13] = (0.4)*CFACTOR;
  FIX[0] = (1800.)*CFACTOR;
  FIX[1] = (1.E9)*CFACTOR;
  FIX[2] = (1.)*CFACTOR;
/* constant rate coefficients                                       */
  RCONST[13] = 4e-12;
  RCONST[15] = 0.0004;
  RCONST[20] = 1.2e-12;
  RCONST[23] = 5.8e-16;
/* END constant rate coefficients                                   */

/* INLINED initializations                                          */

   TSTART = 8.0*3600.0;
   TEND = TSTART + 2.*24.0*3600.0;
   DT = 900.0; // 3600.0;
   TEMP = 298.15;

/* End INLINED initializations                                      */

}

/* End of Initialize function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


