/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Jacobian Data Structures File                             */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_JacobianSP.c                      */
/* Time                 : Tue Feb  1 10:46:30 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_Parameters.h"
#include "tm5_ifs_Global.h"
#include "tm5_ifs_Sparse.h"



/* Sparse Jacobian Data                                             */

 /* Row indexes of the LU Jacobian of variables */

  int  LU_IROW[] = {
       0,  0,  0,  0,  0,  0,  1,  1,  1,  2,  2,  2,
       3,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,
       5,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,
       7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,
       8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,
      10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11,
      11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 13,
      13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13 }; 

 /* Column indexes of the LU Jacobian of variables */

  int  LU_ICOL[] = {
       0,  1,  8,  9, 11, 13,  1,  9, 11,  2,  8, 13,
       3,  5,  6, 10, 13,  4,  7,  8, 13,  4,  5,  6,
       7,  8, 10, 12, 13,  6,  9, 10, 13,  4,  6,  7,
       8,  9, 10, 12, 13,  2,  3,  4,  5,  6,  7,  8,
       9, 10, 12, 13,  1,  6,  8,  9, 10, 11, 12, 13,
       6,  8,  9, 10, 11, 12, 13,  1,  6,  7,  8,  9,
      10, 11, 12, 13,  7,  8,  9, 10, 11, 12, 13,  2,
       3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13 }; 

 /* Compressed row indexes of the LU Jacobian of variables */

  int  LU_CROW[] = {
       0,  6,  9, 12, 17, 21, 29, 33, 41, 52, 60, 67,
      76, 83, 95 }; 

 /* Diagonal indexes of the LU Jacobian of variables */

  int  LU_DIAG[] = {
       0,  6,  9, 12, 17, 22, 29, 35, 47, 55, 63, 73,
      81, 94, 95 }; 


