/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Utility Data Initialization                                      */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_22_Monitor.c                      */
/* Time                 : Wed Oct 12 11:08:37 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs_22.kpp                            */
/* Output root filename : tm5_ifs_22                                */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_22_Parameters.h"
#include "tm5_ifs_22_Global.h"
#include "tm5_ifs_22_Sparse.h"



 /* Names of chemical species */

  char *  SPC_NAMES[] = {
     "H2O2","N2O5","CO","HNO3","ROOH","RH","HCHO","NO2",
     "O3","OH","HO2","NO3","RO2","NO","CH4","M",
     "DUMMY" }; 

 /* Indexes of species to look at */

  int  LOOKAT[] = {
       0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
      12, 13, 14, 15, 16 }; 

 /* Indexes of species to monitor */

  int  MONITOR[] = {
       7,  8, 13 }; 

 /* Names of atoms for mass balance */

  char *  SMASS[] = {
     0 }; 

 /* Equation names */

  char *  EQN_NAMES[] = {
     "   O3 + OH --> HO2       ",
     "  O3 + HO2 --> OH        ",
     "  OH + HO2 --> M         ",
     "     2 HO2 --> H2O2      ",
     " H2O2 + OH --> HO2       ",
     "        OH --> HO2       ",
     "   O3 + NO --> NO2       ",
     "  NO2 + O3 --> NO3       ",
     "  NO3 + NO --> 2 NO2     ",
     " NO2 + NO3 --> N2O5      ",
     "      N2O5 --> NO2 + NO3 ",
     "  HO2 + NO --> NO2 + OH  ",
     "  NO2 + OH --> HNO3      ",
     " HO2 + NO3 --> HNO3      ",
     " HNO3 + OH --> NO3       ",
     "      N2O5 --> 2 HNO3    ",
     "  OH + CH4 --> RO2       ",
     " HO2 + RO2 --> ROOH      ",
     " HO2 + RO2 --> HCHO      ",
     "  RO2 + NO --> HCHO + NO2 + HO2",
     " NO3 + RO2 --> HCHO + NO2 + HO2",
     " ROOH + OH --> 0.4 HCHO + 0.4 OH + 0.6 RO2",
     " HCHO + OH --> CO + HO2  ",
     "HCHO + NO3 --> HNO3      ",
     "   CO + OH --> HO2       ",
     "     2 RO2 --> 1.37 HCHO + 0.74 HO2",
     "   RH + O3 --> 0.56 CO + 1.04 HCHO + 0.33 OH + 0.19 HO2 + 0.31 RO2 ... etc.",
     "   RH + OH --> HCHO + 0.1 OH + 0.7 RO2",
     "  RH + NO3 --> M         ",
     "        O3 --> 2 OH      ",
     "       NO2 --> O3 + NO   ",
     "      N2O5 --> NO2 + NO3 ",
     "       NO3 --> NO2 + O3  ",
     "      ROOH --> HCHO + OH + HO2",
     "      HCHO --> CO        ",
     "      HCHO --> CO + 2 HO2",
     "      H2O2 --> 2 OH      ",
     "     DUMMY --> NO        ",
     "     DUMMY --> RH        ",
     "        O3 --> M         ",
     "        NO --> M         ",
     "       NO2 --> M         ",
     "      HNO3 --> M         ",
     "      H2O2 --> M         ",
     "      HCHO --> M         ",
     "      ROOH --> M         "
      }; 


/* INLINED global variables                                         */

/* End INLINED global variables                                     */

