/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Function of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : mhh_Function.c                            */
/* Time                 : Tue Oct 18 15:45:13 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : mhh.kpp                                   */
/* Output root filename : mhh                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
//#include "mhh_Parameters.h"
//#include "mhh_Global.h"
//#include "mhh_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Fun - time derivatives of variables - Agregate form              */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      Vdot      - Time derivative of variable species concentrations */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Fun( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double Vdot[],                         /* Time derivative of variable species concentrations */
  double A[]
)
{

/* Local variables                                                  */
//double A[NREACT];                        /* Rate for each equation */

// QSSA Auxiliary Variables
  double P_OH, L_OH;
  double P_HO2, L_HO2;
  double P_RO2, L_RO2;
  double P_NO3, L_NO3;
  double P_N2O5, L_N2O5;
  int i_qssa;

  // =========================================================================
  // QSSA Iteration: Solve P = L * F for OH, HO2, RO2, NO3, N2O5
  // =========================================================================
  
  for (i_qssa = 0; i_qssa < 2; i_qssa++) {
      
      // ---------------------------------------------------------------------
      // 1. Solve N2O5 (Index F[7])
      // ---------------------------------------------------------------------
      // Prod: NO2 + NO3 (A9)
      P_N2O5 = RCT[9]*V[6]*F[6];               // A[9]: NO2(V6) + NO3(F6)

      // Loss: N2O5 -> NO2+NO3 (A10), N2O5 -> 2HNO3 (A15), Loss(A31)
      L_N2O5 = RCT[10]                         // A[10]
             + 0.0004                          // A[15] (Hardcoded k)
             + RCT[31];                        // A[31]

      if (L_N2O5 > 1.0e-30)
          F[7] = P_N2O5 / L_N2O5;
      else
          F[7] = 0.0;

      // ---------------------------------------------------------------------
      // 2. Solve NO3 (Index F[6])
      // ---------------------------------------------------------------------
      // Prod: NO2+O3 (A7), N2O5->NO2+NO3 (A10), HNO3+OH (A14)
      P_NO3 = RCT[7]*V[6]*V[7]                 // A[7]: NO2(V6) + O3(V7)
            + RCT[10]*F[7]                     // A[10]: N2O5(F7)
            + RCT[14]*V[0]*F[3];               // A[14]: HNO3(V0) + OH(F3)

      // Loss: NO(A8), NO2(A9), HO2(A13), RO2(A20), HCHO(A23), RH(A28), Loss(A32)
      L_NO3 = RCT[8]*V[8]                      // A[8]: NO(V8)
            + RCT[9]*V[6]                      // A[9]: NO2(V6) (To N2O5)
            + 4.0e-12*F[4]                     // A[13]: HO2(F4) (Hardcoded k)
            + 1.2e-12*F[5]                     // A[20]: RO2(F5) (Hardcoded k)
            + 5.8e-16*V[3]                     // A[23]: HCHO(V3) (Hardcoded k)
            + RCT[28]*V[5]                     // A[28]: RH(V5)
            + RCT[32];                         // A[32]: Loss

      if (L_NO3 > 1.0e-30)
          F[6] = P_NO3 / L_NO3;
      else
          F[6] = 0.0;

      // ---------------------------------------------------------------------
      // 3. Solve RO2 (Index F[5])
      // ---------------------------------------------------------------------
      // Prod: CH4+OH(A16), ROOH+OH(0.6*A21), RH+O3(0.31*A26), RH+OH(A27)
      P_RO2 = RCT[16]*F[3]*F[0]                // A[16]: OH(F3) + CH4(F0)
            + 0.6*RCT[21]*V[4]*F[3]            // A[21]: ROOH(V4) + OH(F3)
            + 0.31*RCT[26]*V[5]*V[7]           // A[26]: RH(V5) + O3(V7)
            + RCT[27]*V[5]*F[3];               // A[27]: RH(V5) + OH(F3)

      // Loss: HO2(A17, A18), NO(A19), NO3(A20), RO2(2*A25)
      L_RO2 = RCT[17]*F[4]                     // A[17]: HO2(F4)
            + RCT[18]*F[4]                     // A[18]: HO2(F4)
            + RCT[19]*V[8]                     // A[19]: NO(V8)
            + 1.2e-12*F[6]                     // A[20]: NO3(F6) (Uses F6 now)
            + 2.0*RCT[25]*F[5];                // A[25]: RO2(F5) - Quadratic

      if (L_RO2 > 1.0e-30)
          F[5] = P_RO2 / L_RO2;
      else
          F[5] = 0.0;

      // ---------------------------------------------------------------------
      // 4. Solve HO2 and OH (Index F[4] F[3])
      // ---------------------------------------------------------------------
      // HO2 Prod: O3+OH(A0), H2O2+OH(A4), OH+M(A5), RO2+NO(A19), RO2+NO3(A20), 
      //       HCHO+OH(A22), CO+OH(A24), RO2+RO2(0.74*A25), RH+O3(0.19*A26),
      //       ROOH+hv(A33), HCHO+hv(2*A35)
      P_HO2 = RCT[0]*V[7]*F[3]                 // A[0]: O3(V7) + OH(F3)
            + RCT[4]*V[1]*F[3]                 // A[4]: H2O2(V1) + OH(F3)
            + RCT[5]*F[3]                      // A[5]: OH(F3)
            + RCT[19]*F[5]*V[8]                // A[19]: RO2(F5) + NO(V8)
            + 1.2e-12*F[6]*F[5]                // A[20]: NO3(F6) + RO2(F5)
            + RCT[22]*V[3]*F[3]                // A[22]: HCHO(V3) + OH(F3)
            + RCT[24]*V[2]*F[3]                // A[24]: CO(V2) + OH(F3)
            + 0.74*RCT[25]*F[5]*F[5]           // A[25]: RO2(F5)^2
            + 0.19*RCT[26]*V[5]*V[7]           // A[26]: RH(V5) + O3(V7)
            + RCT[33]*V[4]                     // A[33]: ROOH(V4)
            + 2.0*RCT[35]*V[3];                // A[35]: HCHO(V3)
      // Loss: O3(A1), OH(A2), HO2(2*A3), NO(A11), NO3(A13), RO2(A17, A18)
      L_HO2 = RCT[1]*V[7]                      // A[1]: O3(V7)
            + RCT[2]*F[3]                      // A[2]: OH(F3)
            + 2.0*RCT[3]*F[4]                  // A[3]: HO2(F4)
            + RCT[11]*V[8]                     // A[11]: NO(V8)
            + 4.0e-12*F[6]                     // A[13]: NO3(F6) (Uses F6 now)
            + RCT[17]*F[5]                     // A[17]: RO2(F5)
            + RCT[18]*F[5];                    // A[18]: RO2(F5)

      if (L_HO2 > 1.0e-30)
          F[4] = P_HO2 / L_HO2;
      else
          F[4] = 0.0;

      // OH Prod: HO2+O3(A1), HO2+NO(A11), RH+O3(0.33*A26), O3+hv(2*A29), 
      //       ROOH+hv(A33), H2O2+hv(2*A36)
      P_OH = RCT[1]*V[7]*F[4]                  // A[1]: O3(V7) + HO2(F4)
           + RCT[11]*F[4]*V[8]                 // A[11]: HO2(F4) + NO(V8)
           + 0.33*RCT[26]*V[5]*V[7]            // A[26]: RH(V5) + O3(V7)
           + 2.0*RCT[29]*V[7]                  // A[29]: O3(V7)
           + RCT[33]*V[4]                      // A[33]: ROOH(V4)
           + 2.0*RCT[36]*V[1];                 // A[36]: H2O2(V1)

      
      // Loss: O3(A0), HO2(A2), H2O2(A4), M(A5), NO2(A12), HNO3(A14), 
      //       CH4(A16), ROOH(0.6*A21), HCHO(A22), CO(A24), RH(A27)
      L_OH = RCT[0]*V[7]                       // A[0]: O3(V7)
           + RCT[2]*F[4]                       // A[2]: HO2(F4)
           + RCT[4]*V[1]                       // A[4]: H2O2(V1)
           + RCT[5]                            // A[5]
           + RCT[12]*V[6]                      // A[12]: NO2(V6)
           + RCT[14]*V[0]                      // A[14]: HNO3(V0)
           + RCT[16]*F[0]                      // A[16]: CH4(F0)
           + 0.6*RCT[21]*V[4]                  // A[21]: ROOH(V4)
           + RCT[22]*V[3]                      // A[22]: HCHO(V3)
           + RCT[24]*V[2]                      // A[24]: CO(V2)
           + RCT[27]*V[5];                     // A[27]: RH(V5)

      if (L_OH > 1.0e-30)
          F[3] = P_OH / L_OH;
      else
          F[3] = 0.0;
      
  }

// Computation of equation rates
  A[0] = RCT[0]*V[7]*F[3];
  A[1] = RCT[1]*V[7]*F[4];
  A[3] = RCT[3]*F[4]*F[4];
  A[4] = RCT[4]*V[1]*F[3];
  A[6] = RCT[6]*V[7]*V[8];
  A[7] = RCT[7]*V[6]*V[7];
  A[8] = RCT[8]*V[8]*F[6];
  A[9] = RCT[9]*V[6]*F[6];
  A[10] = RCT[10]*F[7];
  A[11] = RCT[11]*V[8]*F[4];
  A[12] = RCT[12]*V[6]*F[3];
  A[13] = 4e-12*F[4]*F[6];
  A[14] = RCT[14]*V[0]*F[3];
  A[15] = 0.0004*F[7];
  A[17] = RCT[17]*F[4]*F[5];
  A[18] = RCT[18]*F[4]*F[5];
  A[19] = RCT[19]*V[8]*F[5];
  A[20] = 1.2e-12*F[5]*F[6];
  A[21] = RCT[21]*V[4]*F[3];
  A[22] = RCT[22]*V[3]*F[3];
  A[23] = 5.8e-16*V[3]*F[6];
  A[24] = RCT[24]*V[2]*F[3];
  A[25] = RCT[25]*F[5]*F[5];
  A[26] = RCT[26]*V[5]*V[7];
  A[27] = RCT[27]*V[5]*F[3];
  A[28] = RCT[28]*V[5]*F[6];
  A[29] = RCT[29]*V[7];
  A[30] = RCT[30]*V[6];
  A[31] = RCT[31]*F[7];
  A[32] = RCT[32]*F[6];
  A[33] = RCT[33]*V[4];
  A[34] = RCT[34]*V[3];
  A[35] = RCT[35]*V[3];
  A[36] = RCT[36]*V[1];
  A[37] = RCT[37]*F[2];
  A[38] = RCT[38]*F[2];
  A[39] = RCT[39]*V[7];
  A[40] = RCT[40]*V[8];
  A[41] = RCT[41]*V[6];
  A[42] = RCT[42]*V[0];
  A[43] = RCT[43]*V[1];
  A[44] = RCT[44]*V[3];
  A[45] = RCT[45]*V[4];

// Aggregate function
  Vdot[0] = A[12]+A[13]-A[14]+2*A[15]+A[23]-A[42];
  Vdot[1] = A[3]-A[4]-A[36]-A[43];
  Vdot[2] = A[22]-A[24]+0.56*A[26]+A[34]+A[35];
  Vdot[3] = A[18]+A[19]+A[20]+0.4*A[21]-A[22]-A[23]+1.37*A[25]+1.04
           *A[26]+1.5*A[27]+A[33]-A[34]-A[35]-A[44];
  Vdot[4] = A[17]-A[21]-A[33]-A[45];
  Vdot[5] = -A[26]-A[27]-A[28]+A[38];
  Vdot[6] = A[6]-A[7]+2*A[8]-A[9]+A[10]+A[11]-A[12]+A[19]+A[20]-A[30]
           +A[31]+A[32]-A[41];
  Vdot[7] = -A[0]-A[1]-A[6]-A[7]-A[26]-A[29]+A[30]+A[32]-A[39];
  Vdot[8] = -A[6]-A[8]-A[11]-A[19]+A[30]+A[37]-A[40];
}

/* End of Fun function                                              */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


