/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Parameter Header File                                            */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : mhh_Parameters.h                          */
/* Time                 : Tue Oct 18 15:45:13 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : mhh.kpp                                   */
/* Output root filename : mhh                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */




#define NSPEC                17          /* Number of chemical species */
#define NVAR                 9           /* Number of Variable species */
#define NFAM                 1           /* Number of Prod/Loss Families */
#define NVARACT              9           /* Number of Active species */
#define NFIX                 8           /* Number of Fixed species */
#define NREACT               46          /* Number of reactions */
#define NVARST               0           /* Starting of variables in conc. vect. */
#define NFIXST               9           /* Starting of fixed in conc. vect. */
#define NONZERO              26          /* Number of nonzero entries in Jacobian */
#define LU_NONZERO           26          /* Number of nonzero entries in LU factoriz. of Jacobian */
#define CNVAR                10          /* (NVAR+1) Number of elements in compressed row format */
#define CNEQN                47          /* (NREACT+1) Number stoicm elements in compressed col format */
#define NHESS                9           /* Length of Sparse Hessian */
#define NLOOKAT              17          /* Number of species to look at */
#define NMONITOR             3           /* Number of species to monitor */
#define NMASS                1           /* Number of atoms to check mass balance */

// Index declaration for variable species in C and VAR
//   VAR(ind_spc) = C(ind_spc)

#define ind_HNO3             0          
#define ind_H2O2             1          
#define ind_CO               2          
#define ind_HCHO             3          
#define ind_ROOH             4          
#define ind_RH               5          
#define ind_NO2              6          
#define ind_O3               7          
#define ind_NO               8          

// Index declaration for fixed species in C
//   C(ind_spc)

#define ind_CH4              9          
#define ind_M                10         
#define ind_DUMMY            11         
#define ind_OH               12         
#define ind_HO2              13         
#define ind_RO2              14         
#define ind_NO3              15         
#define ind_N2O5             16         

// Index declaration for fixed species in FIX
//    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

#define indf_CH4             0          
#define indf_M               1          
#define indf_DUMMY           2          
#define indf_OH              3          
#define indf_HO2             4          
#define indf_RO2             5          
#define indf_NO3             6          
#define indf_N2O5            7          

#define NJVRP                34          /* Length of sparse Jacobian JVRP */

#define NSTOICM              65          /* Length of Sparse Stoichiometric Matrix */
