/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Parameter Header File                                            */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_Parameters.h                      */
/* Time                 : Fri Apr 16 15:52:25 2021                  */
/* Working directory    : /home/WUR/szena001/kpp/examples           */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */




#define NSPEC                15          /* Number of chemical species */
#define NVAR                 11          /* Number of Variable species */
#define NVARACT              11          /* Number of Active species */
#define NFIX                 4           /* Number of Fixed species */
#define NREACT               33          /* Number of reactions */
#define NVARST               0           /* Starting of variables in conc. vect. */
#define NFIXST               11          /* Starting of fixed in conc. vect. */
#define NONZERO              45          /* Number of nonzero entries in Jacobian */
#define LU_NONZERO           46          /* Number of nonzero entries in LU factoriz. of Jacobian */
#define CNVAR                12          /* (NVAR+1) Number of elements in compressed row format */
#define CNEQN                34          /* (NREACT+1) Number stoicm elements in compressed col format */
#define NHESS                22          /* Length of Sparse Hessian */
#define NLOOKAT              15          /* Number of species to look at */
#define NMONITOR             3           /* Number of species to monitor */
#define NMASS                1           /* Number of atoms to check mass balance */

/* Index declaration for variable species in C and VAR              */
/*   VAR(ind_spc) = C(ind_spc)                                      */

#define ind_HNO3             0          
#define ind_H2O2             1          
#define ind_CO               2          
#define ind_RH               3          
#define ind_HCHO             4          
#define ind_ROOH             5          
#define ind_NO2              6          
#define ind_HO2              7          
#define ind_O3               8          
#define ind_RO2              9          
#define ind_NO               10         

/* Index declaration for fixed species in C                         */
/*   C(ind_spc)                                                     */

#define ind_CH4              11         
#define ind_M                12         
#define ind_DUMMY            13         
#define ind_OH               14         

/* Index declaration for fixed species in FIX                       */
/*    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 */

#define indf_CH4             0          
#define indf_M               1          
#define indf_DUMMY           2          
#define indf_OH              3          

#define NJVRP                36          /* Length of sparse Jacobian JVRP */

#define NSTOICM              65          /* Length of Sparse Stoichiometric Matrix */
