/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Utility Data Initialization                                      */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_Monitor.c                         */
/* Time                 : Fri Apr 16 15:52:25 2021                  */
/* Working directory    : /home/WUR/szena001/kpp/examples           */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_Parameters.h"
#include "tm5_ifs_Global.h"
#include "tm5_ifs_Sparse.h"



 /* Names of chemical species */

  char *  SPC_NAMES[] = {
     "HNO3","H2O2","CO","RH","HCHO","ROOH","NO2","HO2",
     "O3","RO2","NO","CH4","M","DUMMY","OH" }; 

 /* Indexes of species to look at */

  int  LOOKAT[] = {
       0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
      12, 13, 14 }; 

 /* Indexes of species to monitor */

  int  MONITOR[] = {
       6,  8, 10 }; 

 /* Names of atoms for mass balance */

  char *  SMASS[] = {
     0 }; 

 /* Equation names */

  char *  EQN_NAMES[] = {
     "  O3 + OH --> HO2      ",
     " HO2 + O3 --> OH       ",
     " HO2 + OH --> M        ",
     "    2 HO2 --> H2O2     ",
     "H2O2 + OH --> HO2      ",
     "       OH --> HO2      ",
     "  O3 + NO --> NO2      ",
     " HO2 + NO --> NO2 + OH ",
     " NO2 + OH --> HNO3     ",
     " CH4 + OH --> RO2      ",
     " RO2 + NO --> HCHO + NO2 + HO2",
     "HO2 + RO2 --> ROOH     ",
     "HO2 + RO2 --> HCHO     ",
     "ROOH + OH --> 0.4 HCHO + 0.6 RO2 + 0.4 OH",
     "  CO + OH --> HO2      ",
     "HCHO + OH --> CO + HO2 ",
     "  RH + O3 --> 0.75 RO2 + 0.8 OH",
     "  RH + OH --> RO2      ",
     "       O3 --> 2 OH     ",
     "      NO2 --> O3 + NO  ",
     "     HCHO --> CO + 2 HO2",
     "     HCHO --> CO       ",
     "     ROOH --> HCHO + HO2 + OH",
     "     H2O2 --> 2 OH     ",
     "    DUMMY --> RH       ",
     "    DUMMY --> NO       ",
     "       O3 --> M        ",
     "       NO --> M        ",
     "      NO2 --> M        ",
     "       RH --> M        ",
     "     HNO3 --> M        ",
     "     ROOH --> M        ",
     "     H2O2 --> M        "
      }; 


/* INLINED global variables                                         */

/* End INLINED global variables                                     */

