/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The Stoichiometric Chemical Model File                           */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_Stoichiom.c                       */
/* Time                 : Tue Aug 31 13:57:36 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_Parameters.h"
#include "tm5_ifs_Global.h"
#include "tm5_ifs_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* ReactantProd - Reactant Products in each equation                */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      ARP       - Reactant product in each equation               */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void ReactantProd( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double ARP[]                           /* Reactant product in each equation */
)
{

/* Reactant Products in each equation are useful in the             */
/*     stoichiometric formulation of mass action law                */
  ARP[0] = V[11]*V[15];
  ARP[1] = V[10]*V[11];
  ARP[2] = V[10]*V[15];
  ARP[3] = V[10]*V[10];
  ARP[4] = V[2]*V[15];
  ARP[5] = V[15];
  ARP[6] = V[11]*V[12];
  ARP[7] = V[10]*V[12];
  ARP[8] = V[14]*V[15];
  ARP[9] = V[15]*F[0];
  ARP[10] = V[9]*V[12];
  ARP[11] = V[9]*V[10];
  ARP[12] = V[9]*V[10];
  ARP[13] = V[7]*V[15];
  ARP[14] = V[7]*V[15];
  ARP[15] = V[3]*V[15];
  ARP[16] = V[6]*V[15];
  ARP[17] = V[8]*V[11];
  ARP[18] = V[8]*V[15];
  ARP[19] = V[11];
  ARP[20] = V[14];
  ARP[21] = V[6];
  ARP[22] = V[6];
  ARP[23] = V[7];
  ARP[24] = V[2];
  ARP[25] = V[5]*V[14];
  ARP[26] = V[4];
  ARP[27] = V[4];
  ARP[28] = V[11]*V[14];
  ARP[29] = V[12]*V[13];
  ARP[30] = V[13]*V[14];
  ARP[31] = V[1];
  ARP[32] = V[10]*V[13];
  ARP[33] = V[1];
  ARP[34] = V[8]*V[13];
  ARP[35] = F[2];
  ARP[36] = F[2];
  ARP[37] = V[11];
  ARP[38] = V[12];
  ARP[39] = V[14];
  ARP[40] = V[5];
  ARP[41] = V[0];
  ARP[42] = V[7];
  ARP[43] = V[2];
  ARP[44] = V[6];
  ARP[45] = V[4];
}

/* End of ReactantProd function                                     */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* JacReactantProd - Jacobian of Reactant Products vector           */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)                  */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void JacReactantProd( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double JVRP[]                          /* d ARP(1:NREACT)/d VAR (1:NVAR) */
)
{

/* Reactant Products in each equation are useful in the             */
/*    stoichiometric formulation of mass action law                 */
/* Below we compute the Jacobian of the Reactant Products vector    */
/*    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)      */

/* JVRP(0) = dARP(0)/dV(11)                                         */
  JVRP[0] = V[15];
/* JVRP(1) = dARP(0)/dV(15)                                         */
  JVRP[1] = V[11];
/* JVRP(2) = dARP(1)/dV(10)                                         */
  JVRP[2] = V[11];
/* JVRP(3) = dARP(1)/dV(11)                                         */
  JVRP[3] = V[10];
/* JVRP(4) = dARP(2)/dV(10)                                         */
  JVRP[4] = V[15];
/* JVRP(5) = dARP(2)/dV(15)                                         */
  JVRP[5] = V[10];
/* JVRP(6) = dARP(3)/dV(10)                                         */
  JVRP[6] = 2*V[10];
/* JVRP(7) = dARP(4)/dV(2)                                          */
  JVRP[7] = V[15];
/* JVRP(8) = dARP(4)/dV(15)                                         */
  JVRP[8] = V[2];
/* JVRP(9) = dARP(5)/dV(15)                                         */
  JVRP[9] = 1;
/* JVRP(10) = dARP(6)/dV(11)                                        */
  JVRP[10] = V[12];
/* JVRP(11) = dARP(6)/dV(12)                                        */
  JVRP[11] = V[11];
/* JVRP(12) = dARP(7)/dV(10)                                        */
  JVRP[12] = V[12];
/* JVRP(13) = dARP(7)/dV(12)                                        */
  JVRP[13] = V[10];
/* JVRP(14) = dARP(8)/dV(14)                                        */
  JVRP[14] = V[15];
/* JVRP(15) = dARP(8)/dV(15)                                        */
  JVRP[15] = V[14];
/* JVRP(16) = dARP(9)/dV(15)                                        */
  JVRP[16] = F[0];
/* JVRP(17) = dARP(10)/dV(9)                                        */
  JVRP[17] = V[12];
/* JVRP(18) = dARP(10)/dV(12)                                       */
  JVRP[18] = V[9];
/* JVRP(19) = dARP(11)/dV(9)                                        */
  JVRP[19] = V[10];
/* JVRP(20) = dARP(11)/dV(10)                                       */
  JVRP[20] = V[9];
/* JVRP(21) = dARP(12)/dV(9)                                        */
  JVRP[21] = V[10];
/* JVRP(22) = dARP(12)/dV(10)                                       */
  JVRP[22] = V[9];
/* JVRP(23) = dARP(13)/dV(7)                                        */
  JVRP[23] = V[15];
/* JVRP(24) = dARP(13)/dV(15)                                       */
  JVRP[24] = V[7];
/* JVRP(25) = dARP(14)/dV(7)                                        */
  JVRP[25] = V[15];
/* JVRP(26) = dARP(14)/dV(15)                                       */
  JVRP[26] = V[7];
/* JVRP(27) = dARP(15)/dV(3)                                        */
  JVRP[27] = V[15];
/* JVRP(28) = dARP(15)/dV(15)                                       */
  JVRP[28] = V[3];
/* JVRP(29) = dARP(16)/dV(6)                                        */
  JVRP[29] = V[15];
/* JVRP(30) = dARP(16)/dV(15)                                       */
  JVRP[30] = V[6];
/* JVRP(31) = dARP(17)/dV(8)                                        */
  JVRP[31] = V[11];
/* JVRP(32) = dARP(17)/dV(11)                                       */
  JVRP[32] = V[8];
/* JVRP(33) = dARP(18)/dV(8)                                        */
  JVRP[33] = V[15];
/* JVRP(34) = dARP(18)/dV(15)                                       */
  JVRP[34] = V[8];
/* JVRP(35) = dARP(19)/dV(11)                                       */
  JVRP[35] = 1;
/* JVRP(36) = dARP(20)/dV(14)                                       */
  JVRP[36] = 1;
/* JVRP(37) = dARP(21)/dV(6)                                        */
  JVRP[37] = 1;
/* JVRP(38) = dARP(22)/dV(6)                                        */
  JVRP[38] = 1;
/* JVRP(39) = dARP(23)/dV(7)                                        */
  JVRP[39] = 1;
/* JVRP(40) = dARP(24)/dV(2)                                        */
  JVRP[40] = 1;
/* JVRP(41) = dARP(25)/dV(5)                                        */
  JVRP[41] = V[14];
/* JVRP(42) = dARP(25)/dV(14)                                       */
  JVRP[42] = V[5];
/* JVRP(43) = dARP(26)/dV(4)                                        */
  JVRP[43] = 1;
/* JVRP(44) = dARP(27)/dV(4)                                        */
  JVRP[44] = 1;
/* JVRP(45) = dARP(28)/dV(11)                                       */
  JVRP[45] = V[14];
/* JVRP(46) = dARP(28)/dV(14)                                       */
  JVRP[46] = V[11];
/* JVRP(47) = dARP(29)/dV(12)                                       */
  JVRP[47] = V[13];
/* JVRP(48) = dARP(29)/dV(13)                                       */
  JVRP[48] = V[12];
/* JVRP(49) = dARP(30)/dV(13)                                       */
  JVRP[49] = V[14];
/* JVRP(50) = dARP(30)/dV(14)                                       */
  JVRP[50] = V[13];
/* JVRP(51) = dARP(31)/dV(1)                                        */
  JVRP[51] = 1;
/* JVRP(52) = dARP(32)/dV(10)                                       */
  JVRP[52] = V[13];
/* JVRP(53) = dARP(32)/dV(13)                                       */
  JVRP[53] = V[10];
/* JVRP(54) = dARP(33)/dV(1)                                        */
  JVRP[54] = 1;
/* JVRP(55) = dARP(34)/dV(8)                                        */
  JVRP[55] = V[13];
/* JVRP(56) = dARP(34)/dV(13)                                       */
  JVRP[56] = V[8];
/* JVRP(57) = dARP(37)/dV(11)                                       */
  JVRP[57] = 1;
/* JVRP(58) = dARP(38)/dV(12)                                       */
  JVRP[58] = 1;
/* JVRP(59) = dARP(39)/dV(14)                                       */
  JVRP[59] = 1;
/* JVRP(60) = dARP(40)/dV(5)                                        */
  JVRP[60] = 1;
/* JVRP(61) = dARP(41)/dV(0)                                        */
  JVRP[61] = 1;
/* JVRP(62) = dARP(42)/dV(7)                                        */
  JVRP[62] = 1;
/* JVRP(63) = dARP(43)/dV(2)                                        */
  JVRP[63] = 1;
/* JVRP(64) = dARP(44)/dV(6)                                        */
  JVRP[64] = 1;
/* JVRP(65) = dARP(45)/dV(4)                                        */
  JVRP[65] = 1;
}

/* End of JacReactantProd function                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */



/* Begin Derivative w.r.t. Rate Coefficients                        */


/* End Derivative w.r.t. Rate Coefficients                          */


/* Begin Jacobian Derivative w.r.t. Rate Coefficients               */


/* End Jacobian Derivative w.r.t. Rate Coefficients                 */

