/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The Stoichiometric Chemical Model File                           */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_ohss_Stoichiom.c                  */
/* Time                 : Sat Apr  3 22:32:57 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs_ohss.kpp                          */
/* Output root filename : tm5_ifs_ohss                              */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_ohss_Parameters.h"
#include "tm5_ifs_ohss_Global.h"
#include "tm5_ifs_ohss_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* ReactantProd - Reactant Products in each equation                */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      ARP       - Reactant product in each equation               */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void ReactantProd( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double ARP[]                           /* Reactant product in each equation */
)
{

/* Reactant Products in each equation are useful in the             */
/*     stoichiometric formulation of mass action law                */
  ARP[0] = V[9]*F[1];
  ARP[1] = V[9]*V[11];
  ARP[2] = V[11]*F[1];
  ARP[3] = V[11]*V[11];
  ARP[4] = F[1];
  ARP[5] = V[8]*V[9];
  ARP[6] = V[7]*V[9];
  ARP[7] = V[6]*V[7];
  ARP[8] = V[3];
  ARP[9] = V[8]*V[11];
  ARP[10] = V[7]*F[1];
  ARP[11] = F[0]*F[1];
  ARP[12] = V[8]*V[10];
  ARP[13] = V[10]*V[11];
  ARP[14] = V[4]*F[1];
  ARP[15] = V[1]*F[1];
  ARP[16] = V[2]*F[1];
  ARP[17] = V[5]*V[9];
  ARP[18] = V[5]*F[1];
  ARP[19] = V[5]*V[6];
  ARP[20] = V[9];
  ARP[21] = V[7];
  ARP[22] = V[3];
  ARP[23] = V[2];
  ARP[24] = V[2];
  ARP[25] = V[4];
  ARP[26] = V[6];
  ARP[27] = V[6];
  ARP[28] = V[3];
  ARP[29] = F[3];
  ARP[30] = F[3];
  ARP[31] = V[9];
  ARP[32] = V[8];
  ARP[33] = V[7];
  ARP[34] = V[5];
  ARP[35] = V[0];
  ARP[36] = V[4];
}

/* End of ReactantProd function                                     */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* JacReactantProd - Jacobian of Reactant Products vector           */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)                  */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void JacReactantProd( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double JVRP[]                          /* d ARP(1:NREACT)/d VAR (1:NVAR) */
)
{

/* Reactant Products in each equation are useful in the             */
/*    stoichiometric formulation of mass action law                 */
/* Below we compute the Jacobian of the Reactant Products vector    */
/*    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)      */

/* JVRP(0) = dARP(0)/dV(9)                                          */
  JVRP[0] = F[1];
/* JVRP(1) = dARP(1)/dV(9)                                          */
  JVRP[1] = V[11];
/* JVRP(2) = dARP(1)/dV(11)                                         */
  JVRP[2] = V[9];
/* JVRP(3) = dARP(2)/dV(11)                                         */
  JVRP[3] = F[1];
/* JVRP(4) = dARP(3)/dV(11)                                         */
  JVRP[4] = 2*V[11];
/* JVRP(5) = dARP(5)/dV(8)                                          */
  JVRP[5] = V[9];
/* JVRP(6) = dARP(5)/dV(9)                                          */
  JVRP[6] = V[8];
/* JVRP(7) = dARP(6)/dV(7)                                          */
  JVRP[7] = V[9];
/* JVRP(8) = dARP(6)/dV(9)                                          */
  JVRP[8] = V[7];
/* JVRP(9) = dARP(7)/dV(6)                                          */
  JVRP[9] = V[7];
/* JVRP(10) = dARP(7)/dV(7)                                         */
  JVRP[10] = V[6];
/* JVRP(11) = dARP(8)/dV(3)                                         */
  JVRP[11] = 1;
/* JVRP(12) = dARP(9)/dV(8)                                         */
  JVRP[12] = V[11];
/* JVRP(13) = dARP(9)/dV(11)                                        */
  JVRP[13] = V[8];
/* JVRP(14) = dARP(10)/dV(7)                                        */
  JVRP[14] = F[1];
/* JVRP(15) = dARP(12)/dV(8)                                        */
  JVRP[15] = V[10];
/* JVRP(16) = dARP(12)/dV(10)                                       */
  JVRP[16] = V[8];
/* JVRP(17) = dARP(13)/dV(10)                                       */
  JVRP[17] = V[11];
/* JVRP(18) = dARP(13)/dV(11)                                       */
  JVRP[18] = V[10];
/* JVRP(19) = dARP(14)/dV(4)                                        */
  JVRP[19] = F[1];
/* JVRP(20) = dARP(15)/dV(1)                                        */
  JVRP[20] = F[1];
/* JVRP(21) = dARP(16)/dV(2)                                        */
  JVRP[21] = F[1];
/* JVRP(22) = dARP(17)/dV(5)                                        */
  JVRP[22] = V[9];
/* JVRP(23) = dARP(17)/dV(9)                                        */
  JVRP[23] = V[5];
/* JVRP(24) = dARP(18)/dV(5)                                        */
  JVRP[24] = F[1];
/* JVRP(25) = dARP(19)/dV(5)                                        */
  JVRP[25] = V[6];
/* JVRP(26) = dARP(19)/dV(6)                                        */
  JVRP[26] = V[5];
/* JVRP(27) = dARP(20)/dV(9)                                        */
  JVRP[27] = 1;
/* JVRP(28) = dARP(21)/dV(7)                                        */
  JVRP[28] = 1;
/* JVRP(29) = dARP(22)/dV(3)                                        */
  JVRP[29] = 1;
/* JVRP(30) = dARP(23)/dV(2)                                        */
  JVRP[30] = 1;
/* JVRP(31) = dARP(24)/dV(2)                                        */
  JVRP[31] = 1;
/* JVRP(32) = dARP(25)/dV(4)                                        */
  JVRP[32] = 1;
/* JVRP(33) = dARP(26)/dV(6)                                        */
  JVRP[33] = 1;
/* JVRP(34) = dARP(27)/dV(6)                                        */
  JVRP[34] = 1;
/* JVRP(35) = dARP(28)/dV(3)                                        */
  JVRP[35] = 1;
/* JVRP(36) = dARP(31)/dV(9)                                        */
  JVRP[36] = 1;
/* JVRP(37) = dARP(32)/dV(8)                                        */
  JVRP[37] = 1;
/* JVRP(38) = dARP(33)/dV(7)                                        */
  JVRP[38] = 1;
/* JVRP(39) = dARP(34)/dV(5)                                        */
  JVRP[39] = 1;
/* JVRP(40) = dARP(35)/dV(0)                                        */
  JVRP[40] = 1;
/* JVRP(41) = dARP(36)/dV(4)                                        */
  JVRP[41] = 1;
}

/* End of JacReactantProd function                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */



/* Begin Derivative w.r.t. Rate Coefficients                        */


/* End Derivative w.r.t. Rate Coefficients                          */


/* Begin Jacobian Derivative w.r.t. Rate Coefficients               */


/* End Jacobian Derivative w.r.t. Rate Coefficients                 */

