/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Stoichiometric Data Structures File                       */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_ohss_StoichiomSP.c                */
/* Time                 : Sat Apr  3 22:32:57 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs_ohss.kpp                          */
/* Output root filename : tm5_ifs_ohss                              */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_ohss_Parameters.h"
#include "tm5_ifs_ohss_Global.h"
#include "tm5_ifs_ohss_Sparse.h"



/* Row-compressed sparse data for the Jacobian of reaction products JVRP */
 /* Beginning of rows in JVRP */

  int  CROW_JVRP[] = {
       0,  1,  3,  4,  5,  5,  7,  9, 11, 12, 14, 15,
      15, 17, 19, 20, 21, 22, 24, 25, 27, 28, 29, 30,
      31, 32, 33, 34, 35, 36, 36, 36, 37, 38, 39, 40,
      41, 42 }; 

 /* Column indices in JVRP */

  int  ICOL_JVRP[] = {
       9,  9, 11, 11, 11,  8,  9,  7,  9,  6,  7,  3,
       8, 11,  7,  8, 10, 10, 11,  4,  1,  2,  5,  9,
       5,  5,  6,  9,  7,  3,  2,  2,  4,  6,  6,  3,
       9,  8,  7,  5,  0,  4 }; 

 /* Row indices in JVRP */

  int  IROW_JVRP[] = {
       0,  1,  1,  2,  3,  5,  5,  6,  6,  7,  7,  8,
       9,  9, 10, 12, 12, 13, 13, 14, 15, 16, 17, 17,
      18, 19, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
      31, 32, 33, 34, 35, 36 }; 




/*  Stoichiometric Matrix in Compressed Column Sparse Format        */

 /* Beginning of columns in STOICM */

  int  CCOL_STOICM[] = {
       0,  2,  4,  5,  6,  7, 10, 13, 16, 19, 22, 24,
      25, 30, 33, 36, 38, 41, 44, 46, 50, 51, 54, 57,
      60, 62, 65, 68, 70, 72, 73, 74, 75, 76, 77, 78,
      79, 80 }; 

 /* Row indices in STOICM */

  int  IROW_STOICM[] = {
       9, 11,  9, 11, 11, 11, 11,  7,  8,  9,  6,  7,
       9,  3,  6,  7,  3,  6,  7,  7,  8, 11,  0,  7,
      10,  2,  7,  8, 10, 11,  4, 10, 11,  2,  4, 10,
       1, 11,  1,  2, 11,  5,  9, 10,  5, 10,  5,  6,
       7, 10,  9,  7,  8,  9,  3,  6,  7,  1,  2, 11,
       1,  2,  2,  4, 11,  6,  7,  9,  6,  8,  0,  3,
       5,  8,  9,  8,  7,  5,  0,  4 }; 

 /* Column indices in STOICM */

  int  ICOL_STOICM[] = {
       0,  0,  1,  1,  2,  3,  4,  5,  5,  5,  6,  6,
       6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10,
      11, 12, 12, 12, 12, 12, 13, 13, 13, 14, 14, 14,
      15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 19, 19,
      19, 19, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23,
      24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 28, 28,
      29, 30, 31, 32, 33, 34, 35, 36 }; 

 /* Stoichiometric Matrix in compressed column format */

  double  STOICM[] = {
        -1,    1,   -1,   -1,   -1,   -2,    1,    1,
        -1,   -1,    1,   -1,   -1,    1,   -1,   -1,
        -1,    1,    1,    1,   -1,   -1,    1,   -1,
         1,    1,    1,   -1,   -1,    1,    1,   -1,
        -1,  0.4,   -1,  0.6,   -1,    1,    1,   -1,
         1,   -1,   -1, 0.75,   -1,    1,   -1,   -1,
         1,    1,   -1,   -1,    1,    1,   -1,    1,
         1,    1,   -1,    2,    1,   -1,    1,   -1,
         1,   -1,    1,    1,   -1,    1,    2,   -1,
         1,    1,   -1,   -1,   -1,   -1,   -1,   -1
      }; 


