/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Stoichiometric Data Structures File                       */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : ifs_StoichiomSP.c                         */
/* Time                 : Mon Apr 12 11:55:23 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : ifs.kpp                                   */
/* Output root filename : ifs                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ifs_Parameters.h"
#include "ifs_Global.h"
#include "ifs_Sparse.h"



/* Row-compressed sparse data for the Jacobian of reaction products JVRP */
 /* Beginning of rows in JVRP */

  int  CROW_JVRP[] = {
       0,  1,  3,  4,  5,  5,  6,  8, 10, 12, 13, 13,
      15, 17, 18, 19, 20, 22, 23, 25, 26, 27, 28, 29,
      30, 31, 32, 33, 34, 34, 34, 35, 36, 37, 38, 39,
      40, 41 }; 

 /* Column indices in JVRP */

  int  ICOL_JVRP[] = {
      11,  9, 11,  9,  9,  1,  8, 11,  7, 11,  8,  9,
       7,  8, 10,  9, 10,  4,  2,  3,  5, 11,  5,  5,
       6, 11,  7,  3,  3,  4,  6,  6,  1,  6, 11,  8,
       7,  5,  0,  4,  1 }; 

 /* Row indices in JVRP */

  int  IROW_JVRP[] = {
       0,  1,  1,  2,  3,  5,  6,  6,  7,  7,  8,  8,
       9, 11, 11, 12, 12, 13, 14, 15, 16, 16, 17, 18,
      18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30, 31,
      32, 33, 34, 35, 36 }; 




/*  Stoichiometric Matrix in Compressed Column Sparse Format        */

 /* Beginning of columns in STOICM */

  int  CCOL_STOICM[] = {
       0,  2,  4,  5,  7,  8, 10, 13, 16, 19, 21, 22,
      27, 30, 33, 35, 38, 41, 43, 47, 48, 51, 54, 56,
      59, 62, 64, 65, 67, 68, 69, 70, 71, 72, 73, 74,
      75, 76 }; 

 /* Row indices in STOICM */

  int  IROW_STOICM[] = {
       9, 11,  9, 11,  9,  1,  9,  9,  1,  9,  7,  8,
      11,  6,  7, 11,  7,  8,  9,  0,  7, 10,  3,  7,
       8,  9, 10,  4,  9, 10,  3,  4, 10,  2,  9,  2,
       3,  9,  5, 10, 11,  5, 10,  5,  6,  7, 10, 11,
       7,  8, 11,  2,  3,  9,  2,  3,  3,  4,  9,  6,
       7, 11,  6,  8,  1,  0,  6,  5,  8, 11,  8,  7,
       5,  0,  4,  1 }; 

 /* Column indices in STOICM */

  int  ICOL_STOICM[] = {
       0,  0,  1,  1,  2,  3,  3,  4,  5,  5,  6,  6,
       6,  7,  7,  7,  8,  8,  8,  9,  9, 10, 11, 11,
      11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 15,
      15, 15, 16, 16, 16, 17, 17, 18, 18, 18, 18, 19,
      20, 20, 20, 21, 21, 21, 22, 22, 23, 23, 23, 24,
      24, 24, 25, 25, 26, 27, 27, 28, 29, 30, 31, 32,
      33, 34, 35, 36 }; 

 /* Stoichiometric Matrix in compressed column format */

  double  STOICM[] = {
         1,   -1,   -1,   -1,   -1,    1,   -2,    1,
        -1,    1,    1,   -1,   -1,    1,   -1,   -1,
         1,   -1,   -1,    1,   -1,    1,    1,    1,
        -1,    1,   -1,    1,   -1,   -1,  0.4,   -1,
       0.6,   -1,    1,    1,   -1,    1,   -1, 0.75,
        -1,   -1,    1,   -1,   -1,    1,    1,   -1,
        -1,    1,    1,    1,   -1,    2,    1,   -1,
         1,   -1,    1,   -1,    1,    1,   -1,    1,
        -1,    2,   -1,    1,    1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1 }; 


