/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Function of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_Function.c                        */
/* Time                 : Fri Apr 16 15:52:25 2021                  */
/* Working directory    : /home/WUR/szena001/kpp/examples           */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ifs_Parameters.h"
#include "ifs_Global.h"
#include "ifs_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Fun - time derivatives of variables - Agregate form              */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      Vdot      - Time derivative of variable species concentrations */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Fun( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double Vdot[],                          /* Time derivative of variable species concentrations */
  double A[]
)
{

/* Local variables                                                  */
//double A[NREACT];                        /* Rate for each equation */

/* Computation of equation rates                                    */
  A[0] = RCT[0]*V[8]*F[3];
  A[1] = RCT[1]*V[7]*V[8];
  A[2] = RCT[2]*V[7]*F[3];
  A[3] = RCT[3]*V[7]*V[7];
  A[4] = RCT[4]*V[1]*F[3];
  A[5] = RCT[5]*F[3];
  A[6] = RCT[6]*V[8]*V[10];
  A[7] = RCT[7]*V[7]*V[10];
  A[8] = RCT[8]*V[6]*F[3];
  A[9] = RCT[9]*F[0]*F[3];
  A[10] = RCT[10]*V[9]*V[10];
  A[11] = RCT[11]*V[7]*V[9];
  A[12] = RCT[12]*V[7]*V[9];
  A[13] = RCT[13]*V[5]*F[3];
  A[14] = RCT[14]*V[2]*F[3];
  A[15] = RCT[15]*V[4]*F[3];
  A[16] = 8e-17*V[3]*V[8];
  A[17] = RCT[17]*V[3]*F[3];
  A[18] = RCT[18]*V[8];
  A[19] = RCT[19]*V[6];
  A[20] = RCT[20]*V[4];
  A[21] = RCT[21]*V[4];
  A[22] = RCT[22]*V[5];
  A[23] = RCT[23]*V[1];
  A[24] = RCT[24]*F[2];
  A[25] = RCT[25]*F[2];
  A[26] = RCT[26]*V[8];
  A[27] = RCT[27]*V[10];
  A[28] = RCT[28]*V[6];
  A[29] = RCT[29]*V[3];
  A[30] = RCT[30]*V[0];
  A[31] = RCT[31]*V[5];
  A[32] = RCT[32]*V[1];

/* Aggregate function                                               */
  Vdot[0] = A[8]-A[30];
  Vdot[1] = A[3]-A[4]-A[23]-A[32];
  Vdot[2] = -A[14]+A[15]+A[20]+A[21];
  Vdot[3] = -A[16]-A[17]+A[24]-A[29];
  Vdot[4] = A[10]+A[12]+0.4*A[13]-A[15]-A[20]-A[21]+A[22];
  Vdot[5] = A[11]-A[13]-A[22]-A[31];
  Vdot[6] = A[6]+A[7]-A[8]+A[10]-A[19]-A[28];
  Vdot[7] = A[0]-A[1]-A[2]-2*A[3]+A[4]+A[5]-A[7]+A[10]-A[11]-A[12]
           +A[14]+A[15]+2*A[20]+A[22];
  Vdot[8] = -A[0]-A[1]-A[6]-A[16]-A[18]+A[19]-A[26];
  Vdot[9] = A[9]-A[10]-A[11]-A[12]+0.6*A[13]+0.75*A[16]+A[17];
  Vdot[10] = -A[6]-A[7]-A[10]+A[19]+A[25]-A[27];
}

/* End of Fun function                                              */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


