/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Stoichiometric Data Structures File                       */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : ifss_StoichiomSP.c                        */
/* Time                 : Mon Apr 26 17:13:07 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : ifss.kpp                                  */
/* Output root filename : ifss                                      */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ifss_Parameters.h"
#include "ifss_Global.h"
#include "ifss_Sparse.h"



/* Row-compressed sparse data for the Jacobian of reaction products JVRP */
 /* Beginning of rows in JVRP */

  int  CROW_JVRP[] = {
       0,  1,  3,  4,  5,  5,  6,  8, 10, 11, 11, 13,
      15, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28,
      29, 29, 29, 30, 31, 32, 33, 34, 35, 36 }; 

 /* Column indices in JVRP */

  int  ICOL_JVRP[] = {
       8,  7,  8,  7,  7,  1,  8, 10,  7, 10,  6,  9,
      10,  7,  9,  7,  9,  5,  2,  4,  3,  8,  3,  8,
       6,  4,  4,  5,  1,  8, 10,  6,  3,  0,  5,  1
      }; 

 /* Row indices in JVRP */

  int  IROW_JVRP[] = {
       0,  1,  1,  2,  3,  5,  6,  6,  7,  7,  8, 10,
      10, 11, 11, 12, 12, 13, 14, 15, 16, 16, 17, 18,
      19, 20, 21, 22, 23, 26, 27, 28, 29, 30, 31, 32
      }; 




/*  Stoichiometric Matrix in Compressed Column Sparse Format        */

 /* Beginning of columns in STOICM */

  int  CCOL_STOICM[] = {
       0,  2,  4,  5,  7,  8, 10, 13, 16, 18, 19, 24,
      27, 30, 33, 35, 38, 41, 43, 44, 47, 50, 52, 55,
      56, 57, 58, 59, 60, 61, 62, 63, 64, 65 }; 

 /* Row indices in STOICM */

  int  IROW_STOICM[] = {
       7,  8,  7,  8,  7,  1,  7,  7,  1,  7,  6,  8,
      10,  6,  7, 10,  0,  6,  9,  4,  6,  7,  9, 10,
       5,  7,  9,  4,  7,  9,  4,  5,  9,  2,  7,  2,
       4,  7,  3,  8,  9,  3,  9,  8,  6,  8, 10,  2,
       4,  7,  2,  4,  4,  5,  7,  1,  3, 10,  8, 10,
       6,  3,  0,  5,  1 }; 

 /* Column indices in STOICM */

  int  ICOL_STOICM[] = {
       0,  0,  1,  1,  2,  3,  3,  4,  5,  5,  6,  6,
       6,  7,  7,  7,  8,  8,  9, 10, 10, 10, 10, 10,
      11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 15,
      15, 15, 16, 16, 16, 17, 17, 18, 19, 19, 19, 20,
      20, 20, 21, 21, 22, 22, 22, 23, 24, 25, 26, 27,
      28, 29, 30, 31, 32 }; 

 /* Stoichiometric Matrix in compressed column format */

  double  STOICM[] = {
         1,   -1,   -1,   -1,   -1,    1,   -2,    1,
        -1,    1,    1,   -1,   -1,    1,   -1,   -1,
         1,   -1,    1,    1,    1,    1,   -1,   -1,
         1,   -1,   -1,    1,   -1,   -1,  0.4,   -1,
       0.6,   -1,    1,    1,   -1,    1,   -1,   -1,
      0.75,   -1,    1,   -1,   -1,    1,    1,    1,
        -1,    2,    1,   -1,    1,   -1,    1,   -1,
         1,    1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1 }; 


