/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialization File                                              */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_Initialize.c                      */
/* Time                 : Tue Aug 31 13:57:36 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs.kpp                               */
/* Output root filename : tm5_ifs                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_Parameters.h"
#include "tm5_ifs_Global.h"
#include "tm5_ifs_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialize - function to initialize concentrations               */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Initialize( 
)
{
int i;                                  
double x;                               

  CFACTOR = 2.550000e+10;

  x = (1.E-6)*CFACTOR;
  for( i = 0; i < NVAR; i++ )
    VAR[i] = x;

  x = (1.E-6)*CFACTOR;
  for( i = 0; i < NFIX; i++ )
    FIX[i] = x;

  VAR[0] = (1.)*CFACTOR;
  VAR[1] = (0.0)*CFACTOR;
  VAR[3] = (200.)*CFACTOR;
  VAR[5] = (0.0)*CFACTOR;
  VAR[6] = (1.)*CFACTOR;
  VAR[8] = (0.45)*CFACTOR;
  VAR[9] = (0.0)*CFACTOR;
  VAR[10] = (0.0)*CFACTOR;
  VAR[11] = (68.8)*CFACTOR;
  VAR[12] = (0.138)*CFACTOR;
  VAR[13] = (0.0)*CFACTOR;
  VAR[14] = (0.608)*CFACTOR;
  VAR[15] = (0.0)*CFACTOR;
  FIX[0] = (1800.)*CFACTOR;
  FIX[1] = (1.E9)*CFACTOR;
  FIX[2] = (1.)*CFACTOR;
/* constant rate coefficients                                       */
  RCONST[14] = 2e-11;
  RCONST[17] = 8e-17;
  RCONST[32] = 4e-12;
  RCONST[33] = 1.5e-21;
  RCONST[34] = 4e-12;
/* END constant rate coefficients                                   */

/* INLINED initializations                                          */

   TSTART = 12.0*3600.0;
   TEND = TSTART + 20.*24.0*3600.0;
   DT = 3600.0;
   TEMP = 298;

/* End INLINED initializations                                      */

}

/* End of Initialize function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


