/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Function of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_22_Function.c                     */
/* Time                 : Wed Oct 12 11:08:37 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs_22.kpp                            */
/* Output root filename : tm5_ifs_22                                */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_22_Parameters.h"
#include "tm5_ifs_22_Global.h"
#include "tm5_ifs_22_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Fun - time derivatives of variables - Agregate form              */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      Vdot      - Time derivative of variable species concentrations */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Fun( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double Vdot[],                         /* Time derivative of variable species concentrations */
  double A[]
)
{

/* Computation of equation rates                                    */
  A[0] = RCT[0]*V[8]*V[9];
  A[1] = RCT[1]*V[8]*V[10];
  A[2] = RCT[2]*V[9]*V[10];
  A[3] = RCT[3]*V[10]*V[10];
  A[4] = RCT[4]*V[0]*V[9];
  A[5] = RCT[5]*V[9];
  A[6] = RCT[6]*V[8]*V[13];
  A[7] = RCT[7]*V[7]*V[8];
  A[8] = RCT[8]*V[11]*V[13];
  A[9] = RCT[9]*V[7]*V[11];
  A[10] = RCT[10]*V[1];
  A[11] = RCT[11]*V[10]*V[13];
  A[12] = RCT[12]*V[7]*V[9];
  A[13] = 4e-12*V[10]*V[11];
  A[14] = RCT[14]*V[3]*V[9];
  A[15] = 0.0004*V[1];
  A[16] = RCT[16]*V[9]*F[0];
  A[17] = RCT[17]*V[10]*V[12];
  A[18] = RCT[18]*V[10]*V[12];
  A[19] = RCT[19]*V[12]*V[13];
  A[20] = 1.2e-12*V[11]*V[12];
  A[21] = RCT[21]*V[4]*V[9];
  A[22] = RCT[22]*V[6]*V[9];
  A[23] = 5.8e-16*V[6]*V[11];
  A[24] = RCT[24]*V[2]*V[9];
  A[25] = RCT[25]*V[12]*V[12];
  A[26] = RCT[26]*V[5]*V[8];
  A[27] = RCT[27]*V[5]*V[9];
  A[28] = RCT[28]*V[5]*V[11];
  A[29] = RCT[29]*V[8];
  A[30] = RCT[30]*V[7];
  A[31] = RCT[31]*V[1];
  A[32] = RCT[32]*V[11];
  A[33] = RCT[33]*V[4];
  A[34] = RCT[34]*V[6];
  A[35] = RCT[35]*V[6];
  A[36] = RCT[36]*V[0];
  A[37] = RCT[37]*F[2];
  A[38] = RCT[38]*F[2];
  A[39] = RCT[39]*V[8];
  A[40] = RCT[40]*V[13];
  A[41] = RCT[41]*V[7];
  A[42] = RCT[42]*V[3];
  A[43] = RCT[43]*V[0];
  A[44] = RCT[44]*V[6];
  A[45] = RCT[45]*V[4];

/* Aggregate function                                               */
  Vdot[0] = A[3]-A[4]-A[36]-A[43];
  Vdot[1] = A[9]-A[10]-A[15]-A[31];
  Vdot[2] = A[22]-A[24]+0.56*A[26]+A[34]+A[35];
  Vdot[3] = A[12]+A[13]-A[14]+2*A[15]+A[23]-A[42];
  Vdot[4] = A[17]-A[21]-A[33]-A[45];
  Vdot[5] = -A[26]-A[27]-A[28]+A[38];
  Vdot[6] = A[18]+A[19]+A[20]+0.4*A[21]-A[22]-A[23]+1.37*A[25]+1.04
           *A[26]+A[27]+A[33]-A[34]-A[35]-A[44];
  Vdot[7] = A[6]-A[7]+2*A[8]-A[9]+A[10]+A[11]-A[12]+A[19]+A[20]-A[30]
           +A[31]+A[32]-A[41];
  Vdot[8] = -A[0]-A[1]-A[6]-A[7]-A[26]-A[29]+A[30]+A[32]-A[39];
  Vdot[9] = -A[0]+A[1]-A[2]-A[4]-A[5]+A[11]-A[12]-A[14]-A[16]-0.6*A[21]
           -A[22]-A[24]+0.33*A[26]-0.9*A[27]+2*A[29]+A[33]+2*A[36];
  Vdot[10] = A[0]-A[1]-A[2]-2*A[3]+A[4]+A[5]-A[11]-A[13]-A[17]-A[18]
            +A[19]+A[20]+A[22]+A[24]+0.74*A[25]+0.19*A[26]+A[33]+2
            *A[35];
  Vdot[11] = A[7]-A[8]-A[9]+A[10]-A[13]+A[14]-A[20]-A[23]-A[28]+A[31]
            -A[32];
  Vdot[12] = A[16]-A[17]-A[18]-A[19]-A[20]+0.6*A[21]-2*A[25]+0.31*A[26]
            +0.7*A[27];
  Vdot[13] = -A[6]-A[8]-A[11]-A[19]+A[30]+A[37]-A[40];
}

/* End of Fun function                                              */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


