/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Jacobian Data Structures File                             */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : tm5_ifs_22_JacobianSP.c                   */
/* Time                 : Wed Oct 12 11:08:37 2022                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : tm5_ifs_22.kpp                            */
/* Output root filename : tm5_ifs_22                                */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "tm5_ifs_22_Parameters.h"
#include "tm5_ifs_22_Global.h"
#include "tm5_ifs_22_Sparse.h"



/* Sparse Jacobian Data                                             */

 /* Row indexes of the LU Jacobian of variables */

  int  LU_IROW[] = {
       0,  0,  0,  1,  1,  1,  2,  2,  2,  2,  2,  3,
       3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,
       5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,
       7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
       8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10,
      10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11,
      11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13,
      13, 13, 13, 13, 13 }; 

 /* Column indexes of the LU Jacobian of variables */

  int  LU_ICOL[] = {
       0,  9, 10,  1,  7, 11,  2,  5,  6,  8,  9,  1,
       3,  6,  7,  9, 10, 11,  4,  9, 10, 12,  5,  8,
       9, 11,  4,  5,  6,  8,  9, 10, 11, 12, 13,  1,
       7,  8,  9, 10, 11, 12, 13,  5,  7,  8,  9, 10,
      11, 12, 13,  0,  2,  3,  4,  5,  6,  7,  8,  9,
      10, 11, 12, 13,  0,  2,  4,  5,  6,  8,  9, 10,
      11, 12, 13,  1,  3,  5,  6,  7,  8,  9, 10, 11,
      12, 13,  4,  5,  8,  9, 10, 11, 12, 13,  7,  8,
       9, 10, 11, 12, 13 }; 

 /* Compressed row indexes of the LU Jacobian of variables */

  int  LU_CROW[] = {
       0,  3,  6, 11, 18, 22, 26, 35, 43, 51, 64, 75,
      86, 94,101 }; 

 /* Diagonal indexes of the LU Jacobian of variables */

  int  LU_DIAG[] = {
       0,  3,  6, 12, 18, 22, 28, 36, 45, 59, 71, 83,
      92,100,101 }; 


