/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The Reaction Rates File                                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_Rates.c                           */
/* Time                 : Wed Aug 19 11:17:37 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando.kpp                               */
/* Output root filename : orlando                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_Parameters.h"
#include "orlando_Global.h"
#include "orlando_Sparse.h"



/* Begin Rate Law Functions from KPP_HOME/util/UserRateLaws         */

/*  User-defined Rate Law functions
    Note: the default argument type for rate laws, as read from the equations file, is single precision
         but all the internal calculations are performed in double precision
*/
/* Arrhenius */
double  ARR( float A0, float B0, float C0 )
      {
      double ARR_RES;
                 
      ARR_RES = (double)A0 * exp( -(double)B0/TEMP ) 
                * pow( (TEMP/300.0), (double)C0 );   
           
      return (double)ARR_RES;
      }           


/* Simplified Arrhenius, with two arguments */
/* Note that the argument B0 has a changed sign when compared to ARR */
double  ARR2(  float A0, float B0 )
      {
      double ARR_RES;           

      ARR_RES =  (double)A0 * exp( (double)B0/TEMP );   
           
      return (double)ARR_RES;
      }           


double  EP2( float A0, float C0, float A2, float C2, float A3, float C3)
      {                       
      double K0, K2, K3, EP2_RES;
      
      K0 = (double)A0 * exp( -(double)C0/TEMP );
      K2 = (double)A2 * exp( -(double)C2/TEMP );
      K3 = (double)A3 * exp( -(double)C3/TEMP );
      K3 = K3*CFACTOR*1.0e+6;
      EP2_RES = K0 + K3/( 1.0+K3/K2 );
        
      return (double)EP2_RES;
      }  


double  EP3( float A1, float C1, float A2, float C2) 
      {               
      double K1, K2, EP3_RES;
      
      K1 = (double)A1 * exp(-(double)C1/TEMP);
      K2 = (double)A2 * exp(-(double)C2/TEMP);
      EP3_RES = K1 + K2*(1.0e+6*CFACTOR);
      
      return (double)EP3_RES;
      }    


double  FALL (  float A0, float B0, float C0, float A1, float B1, float C1, float CF)
      {                      
      double K0, K1, FALL_RES;
      
      K0 = (double)A0 * exp(-(double)B0/TEMP)* pow( (TEMP/300.0), (double)C0 );
      K1 = (double)A1 * exp(-(double)B1/TEMP)* pow( (TEMP/300.0), (double)C1 );
      K0 = K0*CFACTOR*1.0e+6;
      K1 = K0/K1;
      FALL_RES = (K0/(1.0+K1))*
           pow( (double)CF, ( 1.0/( 1.0+pow( (log10(K1)),2 ) ) ) );
        
      return (double)FALL_RES;
      }

/* End Rate Law Functions from KPP_HOME/util/UserRateLaws           */


/* Begin INLINED Rate Law Functions                                 */



double  ARRM( double A0, double B0, double C0, double TEMP )
      {
      return A0 * exp( -B0/TEMP ) 
                * pow( (TEMP/300.0), C0 );   
      }           

double usr_O3_hv_H2O( double TEMP, double C_M, double C_H2O, double J_O1D)
      {
      double KH2O;
      double KN2;
      double KO2;
      KH2O = ((double)1.63e-10 *C_H2O * exp((double)60.0/TEMP)  )  ;
      KN2  = ((double)2.15e-11 * exp((double)110.0/TEMP) *(double)0.79*C_M) ;
      KO2  = ((double)3.30e-11 * exp((double)55.0 /TEMP) *(double)0.21*C_M) ;
      return (KH2O *J_O1D) / (KH2O + KN2 + KO2);
      }           

double usr_HO2_HO2( double TEMP, double C_M, double C_H2O )
/* for cesm-consistent reaction labels, equivalent to usr9 */
/* HO2+HO2 -> H2O2+O2 */
/* H2O included in fc calculation, not as reactant */
      {
      double ko;
      double kinf;
      double fc;
      double kr;

      if( C_H2O > (double)0.0 ) 
          {
          ko   = (double)2.3e-13 * exp( (double)600./TEMP );
          kinf = (double)1.7e-33 * C_M * exp( (double)1000./TEMP );
          fc = (double)1.0 + (double)1.4e-21 *C_H2O* exp( (double)2200./TEMP );
          kr = (ko + kinf) * fc; 
          }
      else
          {
          kr = (double)0.0 ;
          }
      return kr;
      }           

double JPL_TROE( double k0_300K, double n, double kinf_300K, double m, 
                 double base, double temp, double cair )

      {
/* !------------------------------------------------------------ */
/* ! ... local variables */
/* !------------------------------------------------------------ */
      double zt_help;
      double k0_T;
      double kinf_T;
      double k_ratio;

      zt_help = (double)300./temp;
      k0_T    = k0_300K   * pow(zt_help,n) * cair ; /* ! k_0   at current T */
      kinf_T  = kinf_300K * pow(zt_help,m)        ; /* ! k_inf at current T */
      k_ratio = k0_T/kinf_T;

      return  k0_T/((double)1.+k_ratio) * 
              pow(base,(double)1.0/
              ((double)1.0+pow(log10(k_ratio),(double)2.0)));
      }           

double usr_N2O5_M( double temp, double c_m )
/* ! for cesm-consistent reaction labels */
/* ! N2O5 + M -> NO2 + NO3 + M */
/* ! CESM writes this as dependent on the NO2+NO3 rate */
/* ! *** if M is included in reactants, must divide TROEE function by [M] */


/*!    usr_N2O5_M = TROEE(3.333e26_dp, 10900._dp, 2.2e-30_dp, 4.4_dp, & */
/*!                       1.4e-12_dp , .7_dp , TEMP, c_m ) /c_m */
/*! WSY: now consistent with T1 MOZART */
      {
      return JPL_TROE((double)1.8e-30,(double)3.,(double)2.8e-11,
             (double)0.,(double)0.6,temp,c_m)
             * (double)1.724e+26 * exp(-(double)10840.0 / temp) / c_m;
      }

double usr_CO_OH_a( double temp, double c_m )
/* ! for cesm-consistent reaction labels, equivalent to usr8 */
/* ! CO+OH -> CO2+HO2 */
      {
      double boltz = 1.38044e-16;
      return (double)1.5e-13 * ((double)1.+ (double)6.e-7*boltz*c_m*temp);
      }

double usr_N2O5_H2O( double k, double c_h2o )
      {
      return k * c_h2o;
      }

double ARR2M( double A0, double B0, double TEMP)
      {
      return A0 * exp( -B0/TEMP );
      }



/* End INLINED Rate Law Functions                                   */

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Update_SUN - update SUN light using TIME                         */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Update_SUN()
{
double SunRise, SunSet;
double Thour, Tlocal, Ttmp; 
const double PI = 3.14159265358979;  

  SunRise = 4.5;
  SunSet  = 19.5;
  Thour = TIME/3600.0;
  Tlocal = Thour - ((int)Thour/24)*24;

  if ( (Tlocal >= SunRise) && (Tlocal <= SunSet) ) {
    Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise);
    if (Ttmp > 0) Ttmp =  Ttmp*Ttmp;
             else Ttmp = -Ttmp*Ttmp;
    SUN = ( 1.0 + cos(PI*Ttmp) )/2.0; 
  } else {
    SUN=0.0;
  }
}
/* End of Update_SUN function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Update_RCONST - function to update rate constants                */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Update_RCONST( 
)
{


/* Begin INLINED RCONST                                             */


double jval[ ] = {4.964E-05, 8.881E-06, 1.172E-02, 2.620E-02, 2.075E-01, 
                  3.848E-05, 5.544E-05, 6.732E-06};
int Pj_o31d = 0;
int Pj_h2o2 = 1;
int Pj_no2  = 2;
int Pj_no3a = 3;
int Pj_no3b = 4;
int Pj_ch2or = 5;
int Pj_ch2om = 6;
int Pj_ch3o2h = 7;
double C_M = FIX[1] ;
double C_H2O = FIX[0] ;


/* End INLINED RCONST                                               */

  RCONST[0] = (usr_O3_hv_H2O(TEMP,C_M,C_H2O,SUN*jval[Pj_o31d]));
  RCONST[1] = (SUN*jval[Pj_no2]);
  RCONST[2] = (SUN*jval[Pj_ch2or]);
  RCONST[3] = (SUN*jval[Pj_ch2om]);
  RCONST[4] = (ARR2M((double)4.8e-11,-(double)250.0,TEMP));
  RCONST[5] = (ARR2M((double)1.70e-12,(double)940.0,TEMP));
  RCONST[6] = (usr_HO2_HO2(TEMP,C_M,C_H2O));
  RCONST[7] = (ARRM((double)2.03e-16,-(double)693.0,(double)4.57,TEMP));
  RCONST[8] = (ARR2M((double)1.4e-12,(double)1310.0,TEMP));
  RCONST[9] = (JPL_TROE(1.8e-30,3.,2.8e-11,0.0,0.6,TEMP,C_M));
  RCONST[10] = (ARR2M((double)1.4e-13,(double)2470.0,TEMP));
  RCONST[11] = (ARR2M((double)3.50e-12,-(double)270.0,TEMP));
  RCONST[12] = (JPL_TROE(2.4e-30,(double)3.0,1.6e-12,-(double)0.10,
              (double)0.60,TEMP,C_M));
  RCONST[13] = (ARR2M((double)1.8E-11,-(double)110.0,TEMP));
  RCONST[14] = ((double)4.0e-12);
  RCONST[15] = (JPL_TROE(1.8e-30,3.,2.8e-11,0.,0.6,TEMP,
              C_M)*1.724e+26*exp(-10840.0/TEMP));
  RCONST[16] = (usr_N2O5_H2O((double)2.5e-22,C_H2O));
  RCONST[17] = (SUN*jval[Pj_no3a]+SUN*jval[Pj_no3b]);
  RCONST[18] = (ARR2M((double)2.80e-12,-(double)300.0,TEMP));
  RCONST[19] = (ARR2M((double)4.10e-13,-(double)750.0,TEMP));
  RCONST[20] = (usr_CO_OH_a(TEMP,C_M));
  RCONST[21] = (ARR2M((double)2.45e-12,(double)1775.0,TEMP));
  RCONST[22] = (ARR2M((double)5.50e-12,-(double)125.0,TEMP));
  RCONST[23] = (ARR2M((double)2.54e-11,-(double)410.0,TEMP));
  RCONST[24] = (ARR2M((double)5.0e-13,-(double)400.0,TEMP));
  RCONST[25] = (ARR2M((double)8.0e-13,-(double)700.0,TEMP));
  RCONST[26] = (ARR2M((double)4.4e-12,-(double)180.0,TEMP));
  RCONST[27] = (ARR2M((double)5.0e-13,-(double)400.0,TEMP));
  RCONST[28] = (ARR2M((double)8.0e-13,-(double)700.0,TEMP));
  RCONST[29] = (ARR2M((double)1.6e+09,(double)8300.0,TEMP));
  RCONST[30] = (ARR2M((double)4.4e-12,-(double)180.0,TEMP));
  RCONST[31] = (ARR2M((double)1.52e-11,-(double)200.0,TEMP));
  RCONST[32] = (SUN*jval[Pj_ch3o2h]);
  RCONST[33] = (ARR2M((double)1.86e-11,-(double)175.0,TEMP));
  RCONST[34] = ((double)0.004*SUN*jval[Pj_no2]);
  RCONST[35] = (ARR2M((double)8.0e-13,-(double)700.0,TEMP));
  RCONST[36] = (ARR2M((double)2.7e-12,-(double)360.0,TEMP));
  RCONST[37] = ((double)2.4e-11);
  RCONST[38] = (ARR2M((double)1.03E-14,(double)1995.0,TEMP));
  RCONST[39] = (ARR2M((double)3.15e-12,(double)450.0,TEMP));
  RCONST[40] = (SUN*jval[Pj_h2o2]);
  RCONST[41] = (vdh2o2);
  RCONST[42] = (vdo3);
  RCONST[43] = (vdno);
  RCONST[44] = (vdno2);
  RCONST[45] = (vdhcho);
  RCONST[46] = (vdisopooh);
  RCONST[47] = (vdhald);
  RCONST[48] = (eno);
  RCONST[49] = (eisop);
  RCONST[50] = (emvkmacr);
}

/* End of Update_RCONST function                                    */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Update_PHOTO - function to update photolytical rate constants    */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Update_PHOTO( 
)
{

}

/* End of Update_PHOTO function                                     */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


