/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Hessian Data Structures File                              */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_ohss_HessianSP.c                  */
/* Time                 : Sun Aug  9 15:18:54 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando_ohss.kpp                          */
/* Output root filename : orlando_ohss                              */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_ohss_Parameters.h"
#include "orlando_ohss_Global.h"
#include "orlando_ohss_Sparse.h"



/* Hessian Sparse Data                                              */
/*                                                                  */
 /* Index i of Hessian element d^2 f_i/dv_j.dv_k */

  int  IHESS_I[] = {
       0,  0,  2,  3,  3,  4,  4,  4,  4,  5,  5,  5,
       5,  5,  5,  5,  6,  6,  7,  7,  8,  8,  8,  9,
       9, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11,
      11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13,
      13, 14, 14, 14, 14, 14, 15, 15, 15, 16, 16, 16,
      16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
      17, 17, 17, 17, 17 }; 

 /* Index j of Hessian element d^2 f_i/dv_j.dv_k */

  int  IHESS_J[] = {
       7, 17, 11, 13, 14,  7,  9, 10, 13,  7,  9, 10,
      10, 13, 13, 14, 10, 15,  7,  7,  7, 10, 10,  9,
       9, 10, 10, 10,  9, 10, 11, 11, 12, 13, 13, 13,
      13, 16,  7, 11, 12, 12,  9, 10, 12, 13, 13, 13,
      13,  7, 10, 13, 14, 14, 13, 14, 15,  7, 11, 11,
      13, 16,  7,  9,  9, 10, 10, 10, 12, 13, 13, 13,
      14, 14, 15, 16, 17 }; 

 /* Index k of Hessian element d^2 f_i/dv_j.dv_k */

  int  IHESS_K[] = {
      12, 17, 16, 15, 15, 12, 13, 13, 15, 12, 13, 13,
      14, 14, 15, 15, 17, 17, 12, 16, 12, 13, 14, 13,
      17, 13, 14, 17, 13, 13, 12, 16, 13, 14, 15, 16,
      17, 17, 12, 12, 13, 17, 13, 13, 13, 14, 15, 16,
      17, 12, 14, 14, 15, 17, 15, 15, 17, 16, 12, 16,
      16, 17, 12, 13, 17, 13, 14, 17, 17, 14, 15, 17,
      15, 17, 17, 17, 17 }; 


