/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Jacobian Data Structures File                             */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_JacobianSP.c                      */
/* Time                 : Wed Aug 19 11:17:37 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando.kpp                               */
/* Output root filename : orlando                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_Parameters.h"
#include "orlando_Global.h"
#include "orlando_Sparse.h"



/* Sparse Jacobian Data                                             */

 /* Row indexes of the LU Jacobian of variables */

  int  LU_IROW[] = {
       0,  0,  1,  1,  1,  1,  2,  2,  2,  3,  3,  3,
       3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
       5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,
       6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  8,
       8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,
       9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 11,
      11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
      12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
      12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14,
      14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16,
      16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17,
      17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
      18, 18, 18, 18, 18, 18, 18 }; 

 /* Column indexes of the LU Jacobian of variables */

  int  LU_ICOL[] = {
       0, 18,  1,  7, 12, 17,  2, 11, 16,  3, 13, 14,
      15, 18,  4,  5,  7,  8, 10, 13, 14, 17, 18,  5,
       6,  7,  8,  9, 10, 13, 14, 15, 17, 18,  6, 10,
      12, 14, 18,  7, 16, 17, 18,  3,  6,  8, 10, 12,
      13, 14, 15, 18,  6,  7,  9, 10, 12, 13, 14, 15,
      16, 17, 18,  7, 10, 12, 13, 15, 16, 17, 18,  2,
       8, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,
       5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17,
      18,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18,  7,
      12, 13, 14, 15, 16, 17, 18,  0,  7,  9, 10, 12,
      13, 14, 15, 16, 17, 18,  2,  7, 11, 12, 13, 14,
      15, 16, 17, 18,  7, 11, 12, 13, 14, 15, 16, 17,
      18,  0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11,
      12, 13, 14, 15, 16, 17, 18 }; 

 /* Compressed row indexes of the LU Jacobian of variables */

  int  LU_CROW[] = {
       0,  2,  6,  9, 14, 23, 34, 39, 43, 52, 63, 71,
      82, 97,107,115,126,136,145,163 }; 

 /* Diagonal indexes of the LU Jacobian of variables */

  int  LU_DIAG[] = {
       0,  2,  6,  9, 14, 23, 34, 39, 45, 54, 64, 74,
      90,101,110,122,133,143,162,163 }; 


