/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Function of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_Function.c                        */
/* Time                 : Wed Aug 19 11:17:37 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando.kpp                               */
/* Output root filename : orlando                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_Parameters.h"
#include "orlando_Global.h"
#include "orlando_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Fun - time derivatives of variables - Agregate form              */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      Vdot      - Time derivative of variable species concentrations */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Fun( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double Vdot[]                          /* Time derivative of variable species concentrations */
)
{

/* Local variables                                                  */
double A[NREACT];                        /* Rate for each equation */

/* Computation of equation rates                                    */
  A[0] = RCT[0]*V[17];
  A[1] = RCT[1]*V[11];
  A[2] = RCT[2]*V[5];
  A[3] = RCT[3]*V[5];
  A[4] = RCT[4]*V[12]*V[18];
  A[5] = RCT[5]*V[17]*V[18];
  A[6] = RCT[6]*V[12]*V[12];
  A[7] = RCT[7]*V[12]*V[17];
  A[8] = RCT[8]*V[13]*V[17];
  A[9] = RCT[9]*V[11]*V[18];
  A[10] = RCT[10]*V[11]*V[17];
  A[11] = RCT[11]*V[12]*V[13];
  A[12] = RCT[12]*V[11]*V[16];
  A[13] = RCT[13]*V[13]*V[16];
  A[14] = RCT[14]*V[12]*V[16];
  A[15] = RCT[15]*V[2];
  A[16] = RCT[16]*V[2];
  A[17] = RCT[17]*V[16];
  A[18] = RCT[18]*V[13]*V[15];
  A[19] = RCT[19]*V[12]*V[15];
  A[20] = RCT[20]*V[4]*V[18];
  A[21] = RCT[21]*V[0]*V[18];
  A[22] = RCT[22]*V[5]*V[18];
  A[23] = RCT[23]*V[7]*V[18];
  A[24] = RCT[24]*V[10]*V[15];
  A[25] = RCT[25]*V[10]*V[12];
  A[26] = RCT[26]*V[10]*V[13];
  A[27] = RCT[27]*V[14]*V[15];
  A[28] = RCT[28]*V[12]*V[14];
  A[29] = RCT[29]*V[14];
  A[30] = RCT[30]*V[13]*V[14];
  A[31] = RCT[31]*V[6]*V[18];
  A[32] = RCT[32]*V[6];
  A[33] = RCT[33]*V[3]*V[18];
  A[34] = RCT[34]*V[3];
  A[35] = RCT[35]*V[8]*V[12];
  A[36] = RCT[36]*V[8]*V[13];
  A[37] = RCT[37]*V[9]*V[18];
  A[38] = RCT[38]*V[7]*V[17];
  A[39] = RCT[39]*V[7]*V[16];
  A[40] = RCT[40]*V[1];
  A[41] = RCT[41]*V[1];
  A[42] = RCT[42]*V[17];
  A[43] = RCT[43]*V[13];
  A[44] = RCT[44]*V[11];
  A[45] = RCT[45]*V[5];
  A[46] = RCT[46]*V[6];
  A[47] = RCT[47]*V[3];
  A[48] = RCT[48]*F[2];
  A[49] = RCT[49]*F[2];
  A[50] = RCT[50]*F[2];

/* Aggregate function                                               */
  Vdot[0] = -A[21];
  Vdot[1] = A[6]+0.29*A[38]-A[40]-A[41];
  Vdot[2] = A[12]-A[15]-A[16];
  Vdot[3] = 0.75*A[27]+A[29]+0.87*A[30]-A[33]-A[34]-A[47];
  Vdot[4] = A[2]+A[3]-A[20]+A[22]+0.9*A[26]+0.15*A[30]+0.25*A[36]+0.363
           *A[38];
  Vdot[5] = -A[2]-A[3]+A[18]-A[22]+1.5*A[24]+0.9*A[26]+0.75*A[27]+0.1
           *A[30]+0.69*A[32]+0.25*A[36]+A[37]+0.785*A[38]-A[45];
  Vdot[6] = A[25]+A[28]-A[31]-A[32]-A[46];
  Vdot[7] = -A[23]-A[38]-A[39]+A[49];
  Vdot[8] = 0.4*A[31]+A[33]-A[35]-A[36];
  Vdot[9] = 0.75*A[24]+0.9*A[26]+0.69*A[32]-A[37]+0.675*A[38]+A[50];
  Vdot[10] = 0.6*A[23]-A[24]-A[25]-A[26];
  Vdot[11] = -A[1]+A[8]-A[9]-A[10]+A[11]-A[12]+2*A[13]+A[14]+A[15]+0.89
            *A[17]+0.99*A[18]+0.9*A[26]+0.9*A[30]+0.9*A[36]-A[44];
  Vdot[12] = 2*A[2]-A[4]+A[5]-2*A[6]-A[7]-A[11]-A[14]+A[18]-A[19]+A[20]
            +A[22]+A[24]-A[25]+0.9*A[26]+A[27]-A[28]+A[29]+0.97*A[30]
            +A[32]+A[34]-A[35]+A[36]+A[37]+0.125*A[38];
  Vdot[13] = A[1]-A[8]-A[11]-A[13]+0.11*A[17]-A[18]-A[26]-A[30]-A[36]
            -A[43]+A[48];
  Vdot[14] = 0.4*A[23]-A[27]-A[28]-A[29]-A[30];
  Vdot[15] = -A[18]-A[19]+A[21]-A[24]-A[27]+1.5*A[37]+0.181*A[38];
  Vdot[16] = A[10]-A[12]-A[13]-A[14]+A[15]-A[17]-A[39];
  Vdot[17] = -A[0]+A[1]-A[5]-A[7]-A[8]-A[10]+0.89*A[17]-A[38]-A[42];
  Vdot[18] = 2*A[0]-A[4]-A[5]+A[7]-A[9]+A[11]+A[14]-A[20]-A[21]-A[22]
            -A[23]-0.4*A[31]-A[33]+A[34]-A[37]+0.205*A[38]+2*A[40];
}

/* End of Fun function                                              */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


