/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialization File                                              */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_Initialize.c                      */
/* Time                 : Wed Aug 19 11:17:37 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando.kpp                               */
/* Output root filename : orlando                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_Parameters.h"
#include "orlando_Global.h"
#include "orlando_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialize - function to initialize concentrations               */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Initialize( 
)
{
int i;                                  
double x;                               

  CFACTOR = 2.550000e+10;

  x = (1.0E-3)*CFACTOR;
  for( i = 0; i < NVAR; i++ )
    VAR[i] = x;

  x = (1.0E-3)*CFACTOR;
  for( i = 0; i < NFIX; i++ )
    FIX[i] = x;

  VAR[0] = (1800.0)*CFACTOR;
  VAR[1] = (2.0)*CFACTOR;
  VAR[2] = (1.0)*CFACTOR;
  VAR[3] = (1.0)*CFACTOR;
  VAR[4] = (150.0)*CFACTOR;
  VAR[5] = (2.0)*CFACTOR;
  VAR[6] = (1.0)*CFACTOR;
  VAR[7] = (5.0)*CFACTOR;
  VAR[8] = (0.1)*CFACTOR;
  VAR[9] = (2.0)*CFACTOR;
  VAR[10] = (0.1)*CFACTOR;
  VAR[11] = (1.0)*CFACTOR;
  VAR[12] = (0.030)*CFACTOR;
  VAR[13] = (1.0)*CFACTOR;
  VAR[14] = (0.1)*CFACTOR;
  VAR[15] = (0.1)*CFACTOR;
  VAR[16] = (0.1)*CFACTOR;
  VAR[17] = (50.0)*CFACTOR;
  VAR[18] = (0.0005)*CFACTOR;
  FIX[0] = (1e7)*CFACTOR;
  FIX[1] = (1e9)*CFACTOR;
/* constant rate coefficients                                       */
/* END constant rate coefficients                                   */

/* INLINED initializations                                          */

   TSTART = 12.0*3600.0;
   TEND = TSTART + 3.0*3600.0;
   DT = 360.0;
   TEMP = 298.15;

/* End INLINED initializations                                      */

}

/* End of Initialize function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


