/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The Stoichiometric Chemical Model File                           */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_ohss_Stoichiom.c                  */
/* Time                 : Sun Aug  9 15:18:54 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando_ohss.kpp                          */
/* Output root filename : orlando_ohss                              */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_ohss_Parameters.h"
#include "orlando_ohss_Global.h"
#include "orlando_ohss_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* ReactantProd - Reactant Products in each equation                */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      ARP       - Reactant product in each equation               */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void ReactantProd( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double ARP[]                           /* Reactant product in each equation */
)
{

/* Reactant Products in each equation are useful in the             */
/*     stoichiometric formulation of mass action law                */
  ARP[0] = V[12];
  ARP[1] = V[11];
  ARP[2] = V[5];
  ARP[3] = V[5];
  ARP[4] = V[17]*F[0];
  ARP[5] = V[12]*F[0];
  ARP[6] = V[17]*V[17];
  ARP[7] = V[12]*V[17];
  ARP[8] = V[12]*V[13];
  ARP[9] = V[11]*F[0];
  ARP[10] = V[11]*V[12];
  ARP[11] = V[13]*V[17];
  ARP[12] = V[11]*V[16];
  ARP[13] = V[13]*V[16];
  ARP[14] = V[16]*V[17];
  ARP[15] = V[2];
  ARP[16] = V[2];
  ARP[17] = V[16];
  ARP[18] = V[13]*V[14];
  ARP[19] = V[14]*V[17];
  ARP[20] = V[4]*F[0];
  ARP[21] = V[1]*F[0];
  ARP[22] = V[5]*F[0];
  ARP[23] = V[7]*F[0];
  ARP[24] = V[10]*V[14];
  ARP[25] = V[10]*V[17];
  ARP[26] = V[10]*V[13];
  ARP[27] = V[14]*V[15];
  ARP[28] = V[15]*V[17];
  ARP[29] = V[15];
  ARP[30] = V[13]*V[15];
  ARP[31] = V[6]*F[0];
  ARP[32] = V[6];
  ARP[33] = V[3]*F[0];
  ARP[34] = V[3];
  ARP[35] = V[9]*V[17];
  ARP[36] = V[9]*V[13];
  ARP[37] = V[8]*F[0];
  ARP[38] = V[7]*V[12];
  ARP[39] = V[7]*V[16];
  ARP[40] = V[0];
  ARP[41] = V[0];
  ARP[42] = V[12];
  ARP[43] = V[13];
  ARP[44] = V[11];
  ARP[45] = V[5];
  ARP[46] = V[6];
  ARP[47] = V[3];
  ARP[48] = F[3];
  ARP[49] = F[3];
  ARP[50] = F[3];
}

/* End of ReactantProd function                                     */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* JacReactantProd - Jacobian of Reactant Products vector           */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)                  */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void JacReactantProd( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double JVRP[]                          /* d ARP(1:NREACT)/d VAR (1:NVAR) */
)
{

/* Reactant Products in each equation are useful in the             */
/*    stoichiometric formulation of mass action law                 */
/* Below we compute the Jacobian of the Reactant Products vector    */
/*    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)      */

/* JVRP(0) = dARP(0)/dV(12)                                         */
  JVRP[0] = 1;
/* JVRP(1) = dARP(1)/dV(11)                                         */
  JVRP[1] = 1;
/* JVRP(2) = dARP(2)/dV(5)                                          */
  JVRP[2] = 1;
/* JVRP(3) = dARP(3)/dV(5)                                          */
  JVRP[3] = 1;
/* JVRP(4) = dARP(4)/dV(17)                                         */
  JVRP[4] = F[0];
/* JVRP(5) = dARP(5)/dV(12)                                         */
  JVRP[5] = F[0];
/* JVRP(6) = dARP(6)/dV(17)                                         */
  JVRP[6] = 2*V[17];
/* JVRP(7) = dARP(7)/dV(12)                                         */
  JVRP[7] = V[17];
/* JVRP(8) = dARP(7)/dV(17)                                         */
  JVRP[8] = V[12];
/* JVRP(9) = dARP(8)/dV(12)                                         */
  JVRP[9] = V[13];
/* JVRP(10) = dARP(8)/dV(13)                                        */
  JVRP[10] = V[12];
/* JVRP(11) = dARP(9)/dV(11)                                        */
  JVRP[11] = F[0];
/* JVRP(12) = dARP(10)/dV(11)                                       */
  JVRP[12] = V[12];
/* JVRP(13) = dARP(10)/dV(12)                                       */
  JVRP[13] = V[11];
/* JVRP(14) = dARP(11)/dV(13)                                       */
  JVRP[14] = V[17];
/* JVRP(15) = dARP(11)/dV(17)                                       */
  JVRP[15] = V[13];
/* JVRP(16) = dARP(12)/dV(11)                                       */
  JVRP[16] = V[16];
/* JVRP(17) = dARP(12)/dV(16)                                       */
  JVRP[17] = V[11];
/* JVRP(18) = dARP(13)/dV(13)                                       */
  JVRP[18] = V[16];
/* JVRP(19) = dARP(13)/dV(16)                                       */
  JVRP[19] = V[13];
/* JVRP(20) = dARP(14)/dV(16)                                       */
  JVRP[20] = V[17];
/* JVRP(21) = dARP(14)/dV(17)                                       */
  JVRP[21] = V[16];
/* JVRP(22) = dARP(15)/dV(2)                                        */
  JVRP[22] = 1;
/* JVRP(23) = dARP(16)/dV(2)                                        */
  JVRP[23] = 1;
/* JVRP(24) = dARP(17)/dV(16)                                       */
  JVRP[24] = 1;
/* JVRP(25) = dARP(18)/dV(13)                                       */
  JVRP[25] = V[14];
/* JVRP(26) = dARP(18)/dV(14)                                       */
  JVRP[26] = V[13];
/* JVRP(27) = dARP(19)/dV(14)                                       */
  JVRP[27] = V[17];
/* JVRP(28) = dARP(19)/dV(17)                                       */
  JVRP[28] = V[14];
/* JVRP(29) = dARP(20)/dV(4)                                        */
  JVRP[29] = F[0];
/* JVRP(30) = dARP(21)/dV(1)                                        */
  JVRP[30] = F[0];
/* JVRP(31) = dARP(22)/dV(5)                                        */
  JVRP[31] = F[0];
/* JVRP(32) = dARP(23)/dV(7)                                        */
  JVRP[32] = F[0];
/* JVRP(33) = dARP(24)/dV(10)                                       */
  JVRP[33] = V[14];
/* JVRP(34) = dARP(24)/dV(14)                                       */
  JVRP[34] = V[10];
/* JVRP(35) = dARP(25)/dV(10)                                       */
  JVRP[35] = V[17];
/* JVRP(36) = dARP(25)/dV(17)                                       */
  JVRP[36] = V[10];
/* JVRP(37) = dARP(26)/dV(10)                                       */
  JVRP[37] = V[13];
/* JVRP(38) = dARP(26)/dV(13)                                       */
  JVRP[38] = V[10];
/* JVRP(39) = dARP(27)/dV(14)                                       */
  JVRP[39] = V[15];
/* JVRP(40) = dARP(27)/dV(15)                                       */
  JVRP[40] = V[14];
/* JVRP(41) = dARP(28)/dV(15)                                       */
  JVRP[41] = V[17];
/* JVRP(42) = dARP(28)/dV(17)                                       */
  JVRP[42] = V[15];
/* JVRP(43) = dARP(29)/dV(15)                                       */
  JVRP[43] = 1;
/* JVRP(44) = dARP(30)/dV(13)                                       */
  JVRP[44] = V[15];
/* JVRP(45) = dARP(30)/dV(15)                                       */
  JVRP[45] = V[13];
/* JVRP(46) = dARP(31)/dV(6)                                        */
  JVRP[46] = F[0];
/* JVRP(47) = dARP(32)/dV(6)                                        */
  JVRP[47] = 1;
/* JVRP(48) = dARP(33)/dV(3)                                        */
  JVRP[48] = F[0];
/* JVRP(49) = dARP(34)/dV(3)                                        */
  JVRP[49] = 1;
/* JVRP(50) = dARP(35)/dV(9)                                        */
  JVRP[50] = V[17];
/* JVRP(51) = dARP(35)/dV(17)                                       */
  JVRP[51] = V[9];
/* JVRP(52) = dARP(36)/dV(9)                                        */
  JVRP[52] = V[13];
/* JVRP(53) = dARP(36)/dV(13)                                       */
  JVRP[53] = V[9];
/* JVRP(54) = dARP(37)/dV(8)                                        */
  JVRP[54] = F[0];
/* JVRP(55) = dARP(38)/dV(7)                                        */
  JVRP[55] = V[12];
/* JVRP(56) = dARP(38)/dV(12)                                       */
  JVRP[56] = V[7];
/* JVRP(57) = dARP(39)/dV(7)                                        */
  JVRP[57] = V[16];
/* JVRP(58) = dARP(39)/dV(16)                                       */
  JVRP[58] = V[7];
/* JVRP(59) = dARP(40)/dV(0)                                        */
  JVRP[59] = 1;
/* JVRP(60) = dARP(41)/dV(0)                                        */
  JVRP[60] = 1;
/* JVRP(61) = dARP(42)/dV(12)                                       */
  JVRP[61] = 1;
/* JVRP(62) = dARP(43)/dV(13)                                       */
  JVRP[62] = 1;
/* JVRP(63) = dARP(44)/dV(11)                                       */
  JVRP[63] = 1;
/* JVRP(64) = dARP(45)/dV(5)                                        */
  JVRP[64] = 1;
/* JVRP(65) = dARP(46)/dV(6)                                        */
  JVRP[65] = 1;
/* JVRP(66) = dARP(47)/dV(3)                                        */
  JVRP[66] = 1;
}

/* End of JacReactantProd function                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */



/* Begin Derivative w.r.t. Rate Coefficients                        */


/* End Derivative w.r.t. Rate Coefficients                          */


/* Begin Jacobian Derivative w.r.t. Rate Coefficients               */


/* End Jacobian Derivative w.r.t. Rate Coefficients                 */

