/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Utility Data Initialization                                      */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_ohss_Monitor.c                    */
/* Time                 : Sun Aug  9 15:18:54 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando_ohss.kpp                          */
/* Output root filename : orlando_ohss                              */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_ohss_Parameters.h"
#include "orlando_ohss_Global.h"
#include "orlando_ohss_Sparse.h"



 /* Names of chemical species */

  char *  SPC_NAMES[] = {
     "H2O2","CH4","N2O5","HALD","CO","HCHO","ISOPOOH","ISOP",
     "MVKMACR","XO2","ISOPAO2","NO2","O3","NO","CH3O2","ISOPBO2",
     "NO3","HO2","OH","H2O","M","DUMMY" }; 

 /* Indexes of species to look at */

  int  LOOKAT[] = {
       0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
      12, 13, 14, 15, 16, 17, 18, 19, 20, 21 }; 

 /* Indexes of species to monitor */

  int  MONITOR[] = {
      12 }; 

 /* Names of atoms for mass balance */

  char *  SMASS[] = {
     0 }; 

 /* Equation names */

  char *  EQN_NAMES[] = {
     "             O3 --> 2 OH           ",
     "            NO2 --> O3 + NO        ",
     "           HCHO --> CO + 2 HO2     ",
     "           HCHO --> CO             ",
     "       HO2 + OH --> H2O            ",
     "        O3 + OH --> HO2            ",
     "          2 HO2 --> H2O2           ",
     "       O3 + HO2 --> OH             ",
     "        O3 + NO --> NO2            ",
     "       NO2 + OH --> M              ",
     "       NO2 + O3 --> NO3            ",
     "       NO + HO2 --> NO2 + OH       ",
     "      NO2 + NO3 --> N2O5           ",
     "       NO + NO3 --> 2 NO2          ",
     "      NO3 + HO2 --> NO2 + OH       ",
     "           N2O5 --> NO2 + NO3      ",
     "           N2O5 --> M              ",
     "            NO3 --> 0.89 NO2 + 0.89 O3 + 0.11 NO",
     "     NO + CH3O2 --> HCHO + 0.99 NO2 + HO2",
     "    CH3O2 + HO2 --> M              ",
     "        CO + OH --> HO2            ",
     "       CH4 + OH --> CH3O2          ",
     "      HCHO + OH --> CO + HO2       ",
     "      ISOP + OH --> 0.6 ISOPAO2 + 0.4 ISOPBO2",
     "ISOPAO2 + CH3O2 --> 1.5 HCHO + 0.75 MVKMACR + HO2",
     "  ISOPAO2 + HO2 --> ISOPOOH        ",
     "   ISOPAO2 + NO --> 0.9 CO + 0.9 HCHO + 0.9 MVKMACR + 0.9 NO2 + 0.9 HO2 ... etc.",
     "CH3O2 + ISOPBO2 --> 0.75 HALD + 0.75 HCHO + HO2",
     "  ISOPBO2 + HO2 --> ISOPOOH        ",
     "        ISOPBO2 --> HALD + HO2     ",
     "   NO + ISOPBO2 --> 0.87 HALD + 0.15 CO + 0.1 HCHO + 0.9 NO2 + 0.97 HO2 ... etc.",
     "   ISOPOOH + OH --> 0.4 XO2 + 0.6 OH",
     "        ISOPOOH --> 0.69 HCHO + 0.69 MVKMACR + HO2",
     "      HALD + OH --> XO2            ",
     "           HALD --> HO2 + OH       ",
     "      XO2 + HO2 --> M              ",
     "       XO2 + NO --> 0.25 CO + 0.25 HCHO + 0.9 NO2 + HO2",
     "   MVKMACR + OH --> HCHO + 1.5 CH3O2 + HO2",
     "      ISOP + O3 --> 0.29 H2O2 + 0.363 CO + 0.785 HCHO + 0.675 MVKMACR + 0.181 CH3O2 ... etc.",
     "     ISOP + NO3 --> M              ",
     "           H2O2 --> 2 OH           ",
     "           H2O2 --> M              ",
     "             O3 --> M              ",
     "             NO --> M              ",
     "            NO2 --> M              ",
     "           HCHO --> M              ",
     "        ISOPOOH --> M              ",
     "           HALD --> M              ",
     "          DUMMY --> NO             ",
     "          DUMMY --> ISOP           ",
     "          DUMMY --> MVKMACR        "
      }; 


/* INLINED global variables                                         */

/* End INLINED global variables                                     */

