/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Hessian Data Structures File                              */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_HessianSP.c                       */
/* Time                 : Wed Aug 19 11:17:37 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando.kpp                               */
/* Output root filename : orlando                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_Parameters.h"
#include "orlando_Global.h"
#include "orlando_Sparse.h"



/* Hessian Sparse Data                                              */
/*                                                                  */
 /* Index i of Hessian element d^2 f_i/dv_j.dv_k */

  int  IHESS_I[] = {
       0,  1,  1,  2,  3,  3,  3,  4,  4,  4,  4,  4,
       4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,
       6,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9,  9,
      10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11,
      11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12,
      12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13,
      13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15,
      15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17,
      17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18,
      18, 18, 18, 18, 18 }; 

 /* Index j of Hessian element d^2 f_i/dv_j.dv_k */

  int  IHESS_J[] = {
       0,  7, 12, 11,  3, 13, 14,  4,  5,  7,  8, 10,
      13,  5,  7,  8,  9, 10, 10, 13, 13, 14,  6, 10,
      12,  7,  7,  7,  3,  6,  8,  8,  7,  9, 10, 10,
       7, 10, 10, 10,  8, 10, 11, 11, 11, 12, 12, 13,
      13, 13, 13,  4,  5,  7,  8,  8,  9, 10, 10, 10,
      12, 12, 12, 12, 12, 12, 12, 13, 13, 14, 17,  8,
      10, 12, 13, 13, 13, 13,  7, 12, 13, 14,  0,  7,
       9, 10, 12, 13, 14,  7, 11, 11, 12, 13,  7, 11,
      12, 13, 17,  0,  3,  4,  5,  6,  7,  7,  9, 11,
      12, 12, 12, 12, 17 }; 

 /* Index k of Hessian element d^2 f_i/dv_j.dv_k */

  int  IHESS_K[] = {
      18, 17, 12, 16, 18, 14, 15, 18, 18, 17, 13, 13,
      14, 18, 17, 13, 18, 13, 15, 14, 15, 15, 18, 12,
      14, 16, 17, 18, 18, 18, 12, 13, 17, 18, 13, 15,
      18, 12, 13, 15, 13, 13, 16, 17, 18, 13, 16, 14,
      15, 16, 17, 18, 18, 17, 12, 13, 18, 12, 13, 15,
      12, 13, 14, 15, 16, 17, 18, 14, 15, 15, 18, 13,
      13, 13, 14, 15, 16, 17, 18, 14, 14, 15, 18, 17,
      18, 15, 15, 15, 15, 16, 16, 17, 16, 16, 17, 17,
      17, 17, 18, 18, 18, 18, 18, 18, 17, 18, 18, 18,
      13, 16, 17, 18, 18 }; 


