/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Stoichiometric Data Structures File                       */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : orlando_ohss_StoichiomSP.c                */
/* Time                 : Sun Aug  9 15:18:54 2020                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : orlando_ohss.kpp                          */
/* Output root filename : orlando_ohss                              */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "orlando_ohss_Parameters.h"
#include "orlando_ohss_Global.h"
#include "orlando_ohss_Sparse.h"



/* Row-compressed sparse data for the Jacobian of reaction products JVRP */
 /* Beginning of rows in JVRP */

  int  CROW_JVRP[] = {
       0,  1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 14,
      16, 18, 20, 22, 23, 24, 25, 27, 29, 30, 31, 32,
      33, 35, 37, 39, 41, 43, 44, 46, 47, 48, 49, 50,
      52, 54, 55, 57, 59, 60, 61, 62, 63, 64, 65, 66,
      67, 67, 67, 67 }; 

 /* Column indices in JVRP */

  int  ICOL_JVRP[] = {
      12, 11,  5,  5, 17, 12, 17, 12, 17, 12, 13, 11,
      11, 12, 13, 17, 11, 16, 13, 16, 16, 17,  2,  2,
      16, 13, 14, 14, 17,  4,  1,  5,  7, 10, 14, 10,
      17, 10, 13, 14, 15, 15, 17, 15, 13, 15,  6,  6,
       3,  3,  9, 17,  9, 13,  8,  7, 12,  7, 16,  0,
       0, 12, 13, 11,  5,  6,  3 }; 

 /* Row indices in JVRP */

  int  IROW_JVRP[] = {
       0,  1,  2,  3,  4,  5,  6,  7,  7,  8,  8,  9,
      10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 16,
      17, 18, 18, 19, 19, 20, 21, 22, 23, 24, 24, 25,
      25, 26, 26, 27, 27, 28, 28, 29, 30, 30, 31, 32,
      33, 34, 35, 35, 36, 36, 37, 38, 38, 39, 39, 40,
      41, 42, 43, 44, 45, 46, 47 }; 




/*  Stoichiometric Matrix in Compressed Column Sparse Format        */

 /* Beginning of columns in STOICM */

  int  CCOL_STOICM[] = {
       0,  1,  4,  7,  9, 10, 12, 14, 16, 19, 20, 23,
      26, 29, 32, 35, 38, 39, 43, 48, 50, 52, 54, 57,
      60, 65, 68, 75, 80, 83, 86, 93, 95, 99,101,103,
     105,111,115,123,125,126,127,128,129,130,131,132,
     133,134,135,136 }; 

 /* Row indices in STOICM */

  int  IROW_STOICM[] = {
      12, 11, 12, 13,  4,  5, 17,  4,  5, 17, 12, 17,
       0, 17, 12, 17, 11, 12, 13, 11, 11, 12, 16, 11,
      13, 17,  2, 11, 16, 11, 13, 16, 11, 16, 17,  2,
      11, 16,  2, 11, 12, 13, 16,  5, 11, 13, 14, 17,
      14, 17,  4, 17,  1, 14,  4,  5, 17,  7, 10, 15,
       5,  8, 10, 14, 17,  6, 10, 17,  4,  5,  8, 10,
      11, 13, 17,  3,  5, 14, 15, 17,  6, 15, 17,  3,
      15, 17,  3,  4,  5, 11, 13, 15, 17,  6,  9,  5,
       6,  8, 17,  3,  9,  3, 17,  9, 17,  4,  5,  9,
      11, 13, 17,  5,  8, 14, 17,  0,  4,  5,  7,  8,
      12, 14, 17,  7, 16,  0,  0, 12, 13, 11,  5,  6,
       3, 13,  7,  8 }; 

 /* Column indices in STOICM */

  int  ICOL_STOICM[] = {
       0,  1,  1,  1,  2,  2,  2,  3,  3,  4,  5,  5,
       6,  6,  7,  7,  8,  8,  8,  9, 10, 10, 10, 11,
      11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15,
      15, 15, 16, 17, 17, 17, 17, 18, 18, 18, 18, 18,
      19, 19, 20, 20, 21, 21, 22, 22, 22, 23, 23, 23,
      24, 24, 24, 24, 24, 25, 25, 25, 26, 26, 26, 26,
      26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 29,
      29, 29, 30, 30, 30, 30, 30, 30, 30, 31, 31, 32,
      32, 32, 32, 33, 33, 34, 34, 35, 35, 36, 36, 36,
      36, 36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 38,
      38, 38, 38, 39, 39, 40, 41, 42, 43, 44, 45, 46,
      47, 48, 49, 50 }; 

 /* Stoichiometric Matrix in compressed column format */

  double  STOICM[] = {
        -1,   -1,    1,    1,    1,   -1,    2,    1,
        -1,   -1,   -1,    1,    1,   -2,   -1,   -1,
         1,   -1,   -1,   -1,   -1,   -1,    1,    1,
        -1,   -1,    1,   -1,   -1,    2,   -1,   -1,
         1,   -1,   -1,   -1,    1,    1,   -1, 0.89,
      0.89, 0.11,   -1,    1, 0.99,   -1,   -1,    1,
        -1,   -1,   -1,    1,   -1,    1,    1,   -1,
         1,   -1,  0.6,  0.4,  1.5, 0.75,   -1,   -1,
         1,    1,   -1,   -1,  0.9,  0.9,  0.9,   -1,
       0.9,   -1,  0.9, 0.75, 0.75,   -1,   -1,    1,
         1,   -1,   -1,    1,   -1,    1, 0.87, 0.15,
       0.1,  0.9,   -1,   -1, 0.97,   -1,  0.4, 0.69,
        -1, 0.69,    1,   -1,    1,   -1,    1,   -1,
        -1, 0.25, 0.25,   -1,  0.9,   -1,    1,    1,
        -1,  1.5,    1, 0.29,0.363,0.785,   -1,0.675,
        -1,0.181,0.125,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,    1,    1,    1
      }; 


